"use client";

import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { useAuth } from "@/context/AuthContext";
import { useState, useEffect, useRef } from "react";

const GROQ_API_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;

// ─── Types ────────────────────────────────────────────────────────────────────
interface AITestimonial {
    quote: string;
    name: string;
    role: string;
    avatar: string;
}

type Lang = "en" | "hi" | "mr";

// ─── Translations ─────────────────────────────────────────────────────────────
const T = {
    en: {
        nav: { how: "How it Works", features: "Features", stories: "Stories", login: "Log in", signup: "Get Started Free", dashboard: "Dashboard" },
        badge: "AI-Powered Learning Assessment",
        heroTop: "Unlock Every Child's",
        taglineFallback: "Unlock Every Child's Learning Potential",
        heroDesc: ["LearnAble uses AI to detect", "Dyslexia", "Dysgraphia", "and", "Dyscalculia", "early — then creates a personalised game-based learning path to help them thrive."],
        startBtn: "🚀 Start Free Assessment",
        howBtn: "See How it Works ↓",
        groqTagline: "Tagline generated by Groq AI ⚡",
        groqStories: "Stories generated by Groq AI ⚡",
        stats: [
            { suffix: " Disorders", label: "Covered" },
            { suffix: "+ games",    label: "Learning Activities" },
            { suffix: " languages", label: "English, Hindi, Marathi" },
            { suffix: "% free",     label: "No credit card needed" },
        ],
        howTitle: "How it Works",
        howSubtitle: "Three simple steps from first visit to personalised learning plan.",
        steps: [
            { title: "Take the Assessment",  desc: "Three short AI-driven tests cover reading, writing, and maths. Takes less than 15 minutes for all three." },
            { title: "Get Your Report",      desc: "Instantly receive a professional-grade screening report with risk levels, AI confidence scores, and recommendations." },
            { title: "Start Learning",       desc: "Jump into a personalised game-based curriculum. XP, streaks, hearts, gems — just like your favourite language app." },
        ],
        checklistItems: ["🔍 AI Screening","📊 Detailed Report","🎮 Game-Based Learning","👨‍👩‍👧 Parent Dashboard","🔊 Text-to-Speech","📥 PDF Export (Hindi/Marathi)"],
        featTitle: "Everything You Need",
        featSubtitle: "LearnAble is the only platform built specifically for learning disabilities in Indian schools.",
        features: [
            { icon: "🧠", title: "AI Diagnosis Engine",     desc: "Neural Network trained on learning patterns detects Dyslexia risk with high accuracy from a 20-question adaptive test.",         accent: "bg-violet-600" },
            { icon: "✍️", title: "Vision AI (Dysgraphia)", desc: "CNN analyses your child's handwriting pixel-by-pixel to detect motor control issues and letter formation errors.",                accent: "bg-teal-600"   },
            { icon: "🧮", title: "Dyscalculia Profiler",    desc: "Timed arithmetic, sequencing, and clock-reading tasks mapped against age norms with response time analysis.",                     accent: "bg-orange-500" },
            { icon: "🎮", title: "10+ Learning Games",      desc: "Phonics, Sight Words, Tracing, Maze Master, Math Race, Shape Sorter — all curriculum-aligned and gamified.",                      accent: "bg-blue-600"   },
            { icon: "📊", title: "Rich Reporting",          desc: "Professional multi-section PDF reports with bar charts, radar charts, and confidence gauges — in English, Hindi & Marathi.",       accent: "bg-fuchsia-600"},
            { icon: "👨‍👩‍👧", title: "Parent Dashboard",   desc: "PIN-protected parent view showing progress charts, session history, and a downloadable report for specialists.",                   accent: "bg-green-600"  },
        ],
        testimonialsTitle: "What Families Say",
        testimonialsSubtitle: "Families across India are using LearnAble to understand their children better.",
        ctaTitle: "Every Child Learns Differently.",
        ctaSubtitle: "Find out how your child learns — for free, in 15 minutes.",
        ctaBtn: "Create Free Account →",
        ctaBtnUser: "Go to Dashboard →",
        ctaNote: "No credit card. No email required for assessment.",
        footerNote: "Made with ❤️ for every child who learns differently.",
    },
    hi: {
        nav: { how: "यह कैसे काम करता है", features: "विशेषताएं", stories: "कहानियां", login: "लॉग इन", signup: "मुफ्त शुरू करें", dashboard: "डैशबोर्ड" },
        badge: "AI-संचालित शिक्षण मूल्यांकन",
        heroTop: "हर बच्चे की",
        taglineFallback: "हर बच्चे की सीखने की क्षमता को उजागर करें",
        heroDesc: ["LearnAble AI का उपयोग करके", "डिस्लेक्सिया", "डिस्ग्राफिया", "और", "डिस्केल्कुलिया", "का जल्दी पता लगाता है — फिर उनके लिए एक व्यक्तिगत गेम-आधारित शिक्षण पथ बनाता है।"],
        startBtn: "🚀 मुफ्त मूल्यांकन शुरू करें",
        howBtn: "यह कैसे काम करता है ↓",
        groqTagline: "Groq AI द्वारा टैगलाइन ⚡",
        groqStories: "Groq AI द्वारा कहानियां ⚡",
        stats: [
            { suffix: " विकार",   label: "कवर किए गए" },
            { suffix: "+ गेम्स",  label: "शिक्षण गतिविधियाँ" },
            { suffix: " भाषाएं",  label: "अंग्रेजी, हिंदी, मराठी" },
            { suffix: "% मुफ्त",  label: "क्रेडिट कार्ड की जरूरत नहीं" },
        ],
        howTitle: "यह कैसे काम करता है",
        howSubtitle: "पहली विजिट से व्यक्तिगत शिक्षण योजना तक तीन सरल चरण।",
        steps: [
            { title: "मूल्यांकन लें",       desc: "तीन छोटे AI-संचालित परीक्षण पढ़ना, लिखना और गणित को कवर करते हैं। तीनों के लिए 15 मिनट से कम।" },
            { title: "अपनी रिपोर्ट पाएं",  desc: "जोखिम स्तर, AI विश्वास स्कोर और सुझावों के साथ तुरंत एक पेशेवर स्क्रीनिंग रिपोर्ट प्राप्त करें।" },
            { title: "सीखना शुरू करें",    desc: "एक व्यक्तिगत गेम-आधारित पाठ्यक्रम में कूदें। XP, स्ट्रीक, हार्ट, जेम्स — अपने पसंदीदा भाषा ऐप की तरह।" },
        ],
        checklistItems: ["🔍 AI स्क्रीनिंग","📊 विस्तृत रिपोर्ट","🎮 गेम-आधारित शिक्षण","👨‍👩‍👧 अभिभावक डैशबोर्ड","🔊 टेक्स्ट-टू-स्पीच","📥 PDF निर्यात (हिंदी/मराठी)"],
        featTitle: "आपको जो चाहिए वह सब",
        featSubtitle: "LearnAble भारतीय स्कूलों में सीखने की अक्षमताओं के लिए विशेष रूप से बना एकमात्र प्लेटफ़ॉर्म है।",
        features: [
            { icon: "🧠", title: "AI निदान इंजन",        desc: "सीखने के पैटर्न पर प्रशिक्षित न्यूरल नेटवर्क 20-प्रश्न अनुकूली परीक्षण से डिस्लेक्सिया जोखिम का पता लगाता है।",   accent: "bg-violet-600" },
            { icon: "✍️", title: "विजन AI (डिस्ग्राफिया)", desc: "CNN आपके बच्चे की हस्तलेखन का पिक्सल-दर-पिक्सल विश्लेषण करता है।",                                              accent: "bg-teal-600"   },
            { icon: "🧮", title: "डिस्केल्कुलिया प्रोफाइलर", desc: "समयबद्ध अंकगणित, अनुक्रमण और घड़ी-पढ़ने के कार्य आयु मानदंडों के विरुद्ध मैप किए गए।",                        accent: "bg-orange-500" },
            { icon: "🎮", title: "10+ शिक्षण गेम्स",      desc: "फोनिक्स, साइट वर्ड्स, ट्रेसिंग, मेज़ मास्टर, मैथ रेस — सभी पाठ्यक्रम-संरेखित और गेमिफाइड।",                    accent: "bg-blue-600"   },
            { icon: "📊", title: "समृद्ध रिपोर्टिंग",      desc: "बार चार्ट, राडार चार्ट और विश्वास गेज के साथ पेशेवर PDF रिपोर्ट — अंग्रेजी, हिंदी और मराठी में।",               accent: "bg-fuchsia-600"},
            { icon: "👨‍👩‍👧", title: "अभिभावक डैशबोर्ड",  desc: "PIN-संरक्षित अभिभावक दृश्य जो प्रगति चार्ट, सत्र इतिहास और विशेषज्ञों के लिए डाउनलोड करने योग्य रिपोर्ट दिखाता है।", accent: "bg-green-600"  },
        ],
        testimonialsTitle: "परिवार क्या कहते हैं",
        testimonialsSubtitle: "भारत भर के परिवार अपने बच्चों को बेहतर समझने के लिए LearnAble का उपयोग कर रहे हैं।",
        ctaTitle: "हर बच्चा अलग तरह से सीखता है।",
        ctaSubtitle: "जानें आपका बच्चा कैसे सीखता है — मुफ्त में, 15 मिनट में।",
        ctaBtn: "मुफ्त अकाउंट बनाएं →",
        ctaBtnUser: "डैशबोर्ड पर जाएं →",
        ctaNote: "कोई क्रेडिट कार्ड नहीं। मूल्यांकन के लिए कोई ईमेल जरूरी नहीं।",
        footerNote: "हर उस बच्चे के लिए ❤️ के साथ बनाया गया जो अलग तरह से सीखता है।",
    },
    mr: {
        nav: { how: "हे कसे कार्य करते", features: "वैशिष्ट्ये", stories: "कथा", login: "लॉग इन", signup: "मोफत सुरू करा", dashboard: "डॅशबोर्ड" },
        badge: "AI-चालित शिक्षण मूल्यांकन",
        heroTop: "प्रत्येक मुलाची",
        taglineFallback: "प्रत्येक मुलाची शिकण्याची क्षमता उघडा",
        heroDesc: ["LearnAble AI वापरून", "डिस्लेक्सिया", "डिस्ग्राफिया", "आणि", "डिस्कॅल्क्युलिया", "लवकर शोधते — मग त्यांच्यासाठी वैयक्तिक गेम-आधारित शिकण्याचा मार्ग तयार करते।"],
        startBtn: "🚀 मोफत मूल्यांकन सुरू करा",
        howBtn: "हे कसे कार्य करते ↓",
        groqTagline: "Groq AI ने टॅगलाइन तयार केली ⚡",
        groqStories: "Groq AI ने कथा तयार केल्या ⚡",
        stats: [
            { suffix: " विकार",   label: "समाविष्ट" },
            { suffix: "+ गेम्स",  label: "शिक्षण क्रियाकलाप" },
            { suffix: " भाषा",    label: "इंग्रजी, हिंदी, मराठी" },
            { suffix: "% मोफत",   label: "क्रेडिट कार्ड नको" },
        ],
        howTitle: "हे कसे कार्य करते",
        howSubtitle: "पहिल्या भेटीपासून वैयक्तिक शिक्षण योजनेपर्यंत तीन सोपे टप्पे।",
        steps: [
            { title: "मूल्यांकन घ्या",       desc: "तीन छोटे AI-चालित चाचण्या वाचन, लेखन आणि गणित कव्हर करतात. तिन्हींसाठी 15 मिनिटांपेक्षा कमी वेळ लागतो." },
            { title: "तुमचा अहवाल मिळवा",   desc: "जोखीम पातळी, AI विश्वास स्कोअर आणि शिफारशींसह त्वरित व्यावसायिक स्क्रीनिंग अहवाल मिळवा." },
            { title: "शिकणे सुरू करा",       desc: "वैयक्तिक गेम-आधारित अभ्यासक्रमात प्रवेश करा. XP, स्ट्रीक, हार्ट, जेम्स — आपल्या आवडत्या भाषा अॅपसारखे." },
        ],
        checklistItems: ["🔍 AI स्क्रीनिंग","📊 तपशीलवार अहवाल","🎮 गेम-आधारित शिक्षण","👨‍👩‍👧 पालक डॅशबोर्ड","🔊 मजकूर-ते-भाषण","📥 PDF निर्यात (हिंदी/मराठी)"],
        featTitle: "तुम्हाला जे हवे ते सर्व",
        featSubtitle: "LearnAble हे भारतीय शाळांमधील शिकण्याच्या अक्षमतांसाठी विशेषतः बनवलेले एकमेव व्यासपीठ आहे।",
        features: [
            { icon: "🧠", title: "AI निदान इंजिन",         desc: "शिकण्याच्या नमुन्यांवर प्रशिक्षित न्यूरल नेटवर्क 20-प्रश्न चाचणीतून डिस्लेक्सिया जोखीम शोधते.",             accent: "bg-violet-600" },
            { icon: "✍️", title: "व्हिजन AI (डिस्ग्राफिया)", desc: "CNN तुमच्या मुलाच्या हस्ताक्षराचे पिक्सेल-दर-पिक्सेल विश्लेषण करते.",                                    accent: "bg-teal-600"   },
            { icon: "🧮", title: "डिस्कॅल्क्युलिया प्रोफाइलर", desc: "वयोमानानुसार मानदंडांविरुद्ध कालबद्ध अंकगणित, अनुक्रम आणि घड्याळ-वाचन कार्ये.",                        accent: "bg-orange-500" },
            { icon: "🎮", title: "10+ शिक्षण गेम्स",        desc: "फोनिक्स, साइट वर्ड्स, ट्रेसिंग, मेज मास्टर, मॅथ रेस — सर्व अभ्यासक्रम-संरेखित आणि गेमिफाइड.",            accent: "bg-blue-600"   },
            { icon: "📊", title: "समृद्ध अहवाल",            desc: "बार चार्ट, रडार चार्ट आणि विश्वास गेजसह व्यावसायिक PDF अहवाल — इंग्रजी, हिंदी आणि मराठीत.",               accent: "bg-fuchsia-600"},
            { icon: "👨‍👩‍👧", title: "पालक डॅशबोर्ड",     desc: "PIN-संरक्षित पालक दृश्य जे प्रगती चार्ट, सत्र इतिहास आणि डाउनलोड करण्यायोग्य अहवाल दाखवते.",              accent: "bg-green-600"  },
        ],
        testimonialsTitle: "कुटुंबे काय म्हणतात",
        testimonialsSubtitle: "भारतभरातील कुटुंबे त्यांच्या मुलांना अधिक चांगल्या प्रकारे समजून घेण्यासाठी LearnAble वापरत आहेत.",
        ctaTitle: "प्रत्येक मूल वेगळ्या प्रकारे शिकते.",
        ctaSubtitle: "तुमचे मूल कसे शिकते ते जाणून घ्या — मोफत, 15 मिनिटांत.",
        ctaBtn: "मोफत खाते तयार करा →",
        ctaBtnUser: "डॅशबोर्डवर जा →",
        ctaNote: "क्रेडिट कार्ड नाही. मूल्यांकनासाठी ईमेल आवश्यक नाही.",
        footerNote: "वेगळ्या प्रकारे शिकणाऱ्या प्रत्येक मुलासाठी ❤️ ने बनवले.",
    },
};

// ─── Fallback testimonials ────────────────────────────────────────────────────
const FALLBACK_TESTIMONIALS: AITestimonial[] = [
    { quote: "My son struggled to read for years. After the assessment, we finally had a name for it — and a plan. The Phonics game is his favourite part of the day now.", name: "Priya Sharma",        role: "Mother of a 9-year-old, Pune",  avatar: "priya"     },
    { quote: "The report we downloaded in Marathi was something we could finally share with my mother-in-law. She understood exactly what her granddaughter needs.",         name: "Aishwarya Kulkarni", role: "Parent, Nashik",                avatar: "aishwarya" },
    { quote: "As a special educator, I recommend LearnAble to every school I work with. The AI confidence scores help me start conversations with parents.",                 name: "Mr. Ramesh Patil",   role: "Special Educator, Mumbai",      avatar: "ramesh"    },
];

// ─── Groq helpers ─────────────────────────────────────────────────────────────
async function fetchAITagline(): Promise<string> {
    const themes = ["hope and discovery","every child is unique","unlocking hidden strengths","seeing the world differently","early support changes everything"];
    const theme = themes[Math.floor(Math.random() * themes.length)];
    const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${GROQ_API_KEY}` },
        body: JSON.stringify({
            model: "llama-3.3-70b-versatile",
            messages: [
                { role: "system", content: "You write punchy 6–10 word hero taglines for an AI learning disability platform for Indian families. Return ONLY the tagline text — no quotes, no punctuation at the end, no explanation." },
                { role: "user", content: `Write a warm, inspiring tagline with the theme: "${theme}". Max 10 words.` },
            ],
            temperature: 1.1, max_tokens: 30,
        }),
    });
    if (!res.ok) throw new Error("Groq tagline error");
    const data = await res.json();
    return data?.choices?.[0]?.message?.content?.trim() || "Unlock Every Child's Learning Potential";
}

async function fetchAITestimonials(): Promise<AITestimonial[]> {
    const seed = Math.random().toString(36).slice(2, 7);
    const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${GROQ_API_KEY}` },
        body: JSON.stringify({
            model: "llama-3.3-70b-versatile",
            messages: [
                { role: "system", content: "You generate realistic testimonials for an AI learning disability assessment platform for Indian families. Return ONLY raw JSON — no markdown, no code fences." },
                { role: "user", content: `Seed: ${seed}. Generate 3 testimonials from Indian parents or educators. Each from a different Indian city. Return JSON array: [{"quote":"...","name":"...","role":"...","avatar":"seed_word"}]. Quotes 2 sentences, warm and specific. Real Indian names.` },
            ],
            temperature: 1.0, max_tokens: 600,
        }),
    });
    if (!res.ok) throw new Error("Groq testimonials error");
    const data = await res.json();
    const raw = data?.choices?.[0]?.message?.content || "[]";
    try {
        const fence = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
        const clean = fence ? fence[1] : raw;
        const arr = clean.match(/\[[\s\S]*\]/);
        return arr ? JSON.parse(arr[0]) : [];
    } catch { return []; }
}

// ─── Animated counter ─────────────────────────────────────────────────────────
function Counter({ target, suffix = "" }: { target: number; suffix?: string }) {
    const [val, setVal] = useState(0);
    useEffect(() => {
        let start = 0;
        const step = Math.ceil(target / 60);
        const timer = setInterval(() => {
            start += step;
            if (start >= target) { setVal(target); clearInterval(timer); } else setVal(start);
        }, 20);
        return () => clearInterval(timer);
    }, [target]);
    return <>{val.toLocaleString()}{suffix}</>;
}

// ─── Feature card ─────────────────────────────────────────────────────────────
function FeatureCard({ icon, title, desc, accent }: { icon: string; title: string; desc: string; accent: string }) {
    return (
        <div className="group relative p-6 rounded-2xl border border-gray-700 bg-gray-800/60 shadow-lg shadow-yellow-500/40 hover:shadow-xl hover:shadow-yellow-400/60 hover:-translate-y-1 transition-all duration-300 overflow-hidden backdrop-blur-sm">
            <div className={`absolute inset-0 opacity-0 group-hover:opacity-10 transition-opacity duration-300 ${accent}`} />
            <div className="text-4xl mb-4">{icon}</div>
            <h3 className="font-bold text-lg text-white mb-2">{title}</h3>
            <p className="text-gray-400 text-sm leading-relaxed">{desc}</p>
        </div>
    );
}

// ─── Step card ────────────────────────────────────────────────────────────────
function Step({ n, title, desc, color }: { n: string; title: string; desc: string; color: string }) {
    return (
        <div className="flex gap-5">
            <div className={`w-12 h-12 rounded-full ${color} text-white font-bold text-lg flex items-center justify-center shrink-0 shadow-lg`}>{n}</div>
            <div>
                <h4 className="font-bold text-white mb-1">{title}</h4>
                <p className="text-gray-400 text-sm leading-relaxed">{desc}</p>
            </div>
        </div>
    );
}

// ─── Testimonial card ─────────────────────────────────────────────────────────
function TestimonialCard({ quote, name, role, avatar }: AITestimonial) {
    return (
        <div className="bg-gray-800/70 rounded-2xl p-6 shadow-lg shadow-green-700/50 border border-gray-700 h-full flex flex-col justify-between backdrop-blur-sm">
            <p className="text-gray-300 text-sm leading-relaxed mb-5">&ldquo;{quote}&rdquo;</p>
            <div className="flex items-center gap-3">
                <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${avatar}`} alt={name} className="w-10 h-10 rounded-full bg-violet-900" />
                <div>
                    <p className="font-semibold text-white text-sm">{name}</p>
                    <p className="text-gray-500 text-xs">{role}</p>
                </div>
            </div>
        </div>
    );
}

// ─── Skeleton loader ──────────────────────────────────────────────────────────
function TestimonialSkeleton() {
    return (
        <div className="bg-gray-800/70 rounded-2xl p-6 border border-gray-700 animate-pulse">
            <div className="h-3 bg-gray-700 rounded mb-2 w-full" />
            <div className="h-3 bg-gray-700 rounded mb-2 w-4/5" />
            <div className="h-3 bg-gray-700 rounded mb-5 w-3/5" />
            <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-gray-700" />
                <div className="space-y-1.5">
                    <div className="h-3 bg-gray-700 rounded w-24" />
                    <div className="h-2.5 bg-gray-700 rounded w-32" />
                </div>
            </div>
        </div>
    );
}

// ─── Pill ─────────────────────────────────────────────────────────────────────
function Pill({ label, color }: { label: string; color: string }) {
    return <span className={`px-3 py-1 rounded-full text-xs font-bold ${color}`}>{label}</span>;
}

// ─── Language Switcher ────────────────────────────────────────────────────────
function LangSwitcher({ lang, setLang }: { lang: Lang; setLang: (l: Lang) => void }) {
    const langs: { code: Lang; label: string }[] = [
        { code: "en", label: "EN" },
        { code: "hi", label: "हि" },
        { code: "mr", label: "म" },
    ];
    return (
        <div className="flex items-center gap-1 bg-gray-800 border border-gray-700 rounded-full px-1 py-1">
            {langs.map(({ code, label }) => (
                <button
                    key={code}
                    onClick={() => setLang(code)}
                    className={`px-3 py-1 rounded-full text-xs font-bold transition-all duration-200 ${
                        lang === code
                            ? "bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white shadow-md"
                            : "text-gray-400 hover:text-white"
                    }`}
                >
                    {label}
                </button>
            ))}
        </div>
    );
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function Home() {
    const { user } = useAuth();

    const [lang, setLang] = useState<Lang>("en");
    const t = T[lang];

    const [aiTagline, setAiTagline] = useState<string>("");
    const [taglineLoading, setTaglineLoading] = useState(true);
    const [testimonials, setTestimonials] = useState<AITestimonial[]>([]);
    const [testimonialsLoading, setTestimonialsLoading] = useState(true);
    const hasFetched = useRef(false);

    useEffect(() => {
        if (hasFetched.current) return;
        hasFetched.current = true;
        fetchAITagline()
            .then((t) => setAiTagline(t))
            .catch(() => setAiTagline(""))
            .finally(() => setTaglineLoading(false));
        fetchAITestimonials()
            .then((t) => setTestimonials(t.length ? t : FALLBACK_TESTIMONIALS))
            .catch(() => setTestimonials(FALLBACK_TESTIMONIALS))
            .finally(() => setTestimonialsLoading(false));
    }, []);

    const displayTagline = aiTagline || t.taglineFallback;

    return (
        <div className="min-h-screen bg-gray-950 font-sans">

            {/* ── NAV ── */}
            <nav className="sticky top-0 z-50 bg-gray-900/80 backdrop-blur-md border-b border-gray-800 shadow-sm">
                <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-2 font-extrabold text-xl">
                        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-600 to-fuchsia-500 flex items-center justify-center text-white font-bold shadow-md">L</div>
                        <span className="bg-clip-text text-transparent bg-gradient-to-r from-violet-400 to-fuchsia-400">LearnAble</span>
                    </div>
                    <div className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-400">
                        <a href="#how"          className="hover:text-violet-400 transition-colors">{t.nav.how}</a>
                        <a href="#features"     className="hover:text-violet-400 transition-colors">{t.nav.features}</a>
                        <a href="#testimonials" className="hover:text-violet-400 transition-colors">{t.nav.stories}</a>
                    </div>
                    <div className="flex items-center gap-3">
                        {/* ── Language Switcher ── */}
                        <LangSwitcher lang={lang} setLang={setLang} />

                        {user ? (
                            <div className="flex items-center gap-3">
                                <Link href="/dashboard">
                                    <Button className="rounded-full px-5 py-2 bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white text-sm font-semibold shadow-md hover:shadow-violet-700 transition-all">
                                        {t.nav.dashboard}
                                    </Button>
                                </Link>
                                <Link href="/profile">
                                    <div className="flex items-center gap-2 bg-gray-800 hover:bg-gray-700 px-3 py-1.5 rounded-full cursor-pointer transition-all border border-gray-700">
                                        <img src={user.profileImage || `https://api.dicebear.com/7.x/avataaars/svg?seed=${user.name}`} alt="Profile" className="w-7 h-7 rounded-full" />
                                        <span className="text-sm font-medium text-gray-200 max-w-[100px] truncate">{user.name}</span>
                                    </div>
                                </Link>
                            </div>
                        ) : (
                            <>
                                <Link href="/login" className="text-sm font-medium text-gray-400 hover:text-violet-400 transition-colors">{t.nav.login}</Link>
                                <Link href="/signup">
                                    <Button className="rounded-full px-5 py-2 bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white text-sm font-semibold shadow-md hover:shadow-violet-700 transition-all">
                                        {t.nav.signup}
                                    </Button>
                                </Link>
                            </>
                        )}
                    </div>
                </div>
            </nav>

            {/* ── HERO ── */}
            <section className="relative overflow-hidden pt-24 pb-32 px-6">
                <div className="absolute -top-24 -left-24 w-[500px] h-[500px] bg-violet-900 rounded-full blur-[120px] opacity-30 pointer-events-none" />
                <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-fuchsia-900 rounded-full blur-[120px] opacity-25 pointer-events-none" />
                <div className="absolute bottom-0 left-1/2 w-[300px] h-[300px] bg-blue-900 rounded-full blur-[100px] opacity-20 pointer-events-none" />

                <div className="max-w-5xl mx-auto text-center relative z-10">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-violet-900/60 border border-violet-700 text-violet-300 text-sm font-semibold mb-8 shadow-sm">
                        <span className="w-2 h-2 rounded-full bg-violet-400 animate-pulse" />
                        {t.badge}
                    </div>

                    <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 leading-tight">
                        <span className="text-gray-100">{t.heroTop}</span><br />
                        {taglineLoading ? (
                            <span className="inline-block bg-gray-800 animate-pulse rounded-xl h-16 w-96 align-middle" />
                        ) : (
                            <span className="bg-clip-text text-transparent bg-gradient-to-r from-violet-400 via-fuchsia-400 to-pink-400">
                                {displayTagline}
                            </span>
                        )}
                    </h1>

                    {!taglineLoading && (
                        <div className="inline-flex items-center gap-1.5 text-xs text-gray-500 mb-3">
                            <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                            {t.groqTagline}
                        </div>
                    )}

                    <p className="text-lg md:text-xl text-gray-400 max-w-2xl mx-auto mb-10 leading-relaxed">
                        {t.heroDesc[0]}{" "}
                        <strong className="text-gray-200">{t.heroDesc[1]}</strong>,{" "}
                        <strong className="text-gray-200">{t.heroDesc[2]}</strong>{" "}
                        {t.heroDesc[3]}{" "}
                        <strong className="text-gray-200">{t.heroDesc[4]}</strong>{" "}
                        {t.heroDesc[5]}
                    </p>

                    <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
                        <Link href="/assessment/dyslexia">
                            <Button className="h-14 px-10 text-base font-bold rounded-2xl bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white shadow-xl shadow-violet-900/50 hover:shadow-violet-700 hover:-translate-y-0.5 transition-all duration-300">
                                {t.startBtn}
                            </Button>
                        </Link>
                        <a href="#how">
                            <Button variant="secondary" className="h-14 px-10 text-base font-semibold rounded-2xl border-2 border-gray-700 bg-gray-800/60 text-gray-300 hover:border-violet-600 hover:text-violet-300 transition-all duration-300">
                                {t.howBtn}
                            </Button>
                        </a>
                    </div>

                    <div className="flex flex-wrap justify-center gap-3">
                        <Pill label="📖 Dyslexia"         color="bg-violet-900/60 text-violet-300 border border-violet-700" />
                        <Pill label="✍️ Dysgraphia"       color="bg-teal-900/60 text-teal-300 border border-teal-700" />
                        <Pill label="🧮 Dyscalculia"      color="bg-orange-900/60 text-orange-300 border border-orange-700" />
                        <Pill label="🧠 AI Powered"       color="bg-blue-900/60 text-blue-300 border border-blue-700" />
                        <Pill label="🇮🇳 Hindi & Marathi"  color="bg-green-900/60 text-green-300 border border-green-700" />
                    </div>
                </div>
            </section>

            {/* ── STATS ── */}
            <section className="bg-gray-900 border-y border-gray-800 py-14 px-6">
                <div className="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
                    {[3, 20, 3, 100].map((val, i) => (
                        <div key={i}>
                            <p className="text-4xl font-extrabold text-violet-400 mb-1">
                                <Counter target={val} suffix={t.stats[i].suffix} />
                            </p>
                            <p className="text-sm text-gray-500">{t.stats[i].label}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* ── HOW IT WORKS ── */}
            <section id="how" className="py-24 px-6 bg-gray-950">
                <div className="max-w-4xl mx-auto">
                    <h2 className="text-3xl md:text-4xl font-extrabold text-white text-center mb-4">{t.howTitle}</h2>
                    <p className="text-center text-gray-500 mb-16 max-w-xl mx-auto">{t.howSubtitle}</p>
                    <div className="grid md:grid-cols-2 gap-12 items-center">
                        <div className="space-y-8">
                            <Step n="1" title={t.steps[0].title} desc={t.steps[0].desc} color="bg-violet-600" />
                            <Step n="2" title={t.steps[1].title} desc={t.steps[1].desc} color="bg-fuchsia-500" />
                            <Step n="3" title={t.steps[2].title} desc={t.steps[2].desc} color="bg-orange-500" />
                        </div>
                        <div className="bg-gradient-to-br from-violet-700 to-fuchsia-600 rounded-3xl p-8 text-white shadow-2xl shadow-violet-900/50">
                            <div className="space-y-4">
                                {t.checklistItems.map((f, i) => (
                                    <div key={i} className="flex items-center gap-3">
                                        <div className="w-5 h-5 rounded-full bg-white/20 flex items-center justify-center text-xs">✓</div>
                                        <span className="text-white/90 text-sm font-medium">{f}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ── FEATURES ── */}
            <section id="features" className="bg-gray-900 py-24 px-6">
                <div className="max-w-6xl mx-auto">
                    <h2 className="text-3xl md:text-4xl font-extrabold text-white text-center mb-4">{t.featTitle}</h2>
                    <p className="text-center text-gray-500 mb-16 max-w-xl mx-auto">{t.featSubtitle}</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                        {t.features.map((f, i) => <FeatureCard key={i} {...f} />)}
                    </div>
                </div>
            </section>

            {/* ── TESTIMONIALS ── */}
            <section id="testimonials" className="py-24 px-6 bg-gray-950 shadow-lg shadow-green-700">
                <div className="max-w-5xl mx-auto">
                    <div className="text-center mb-4">
                        <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-2">{t.testimonialsTitle}</h2>
                        {!testimonialsLoading && (
                            <span className="inline-flex items-center gap-1.5 text-xs text-gray-500">
                                <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                                {t.groqStories}
                            </span>
                        )}
                    </div>
                    <p className="text-center text-gray-500 mb-16 max-w-xl mx-auto">{t.testimonialsSubtitle}</p>
                    <div className="grid md:grid-cols-3 gap-6">
                        {testimonialsLoading
                            ? [1, 2, 3].map((i) => <TestimonialSkeleton key={i} />)
                            : testimonials.map((t, i) => <TestimonialCard key={i} {...t} />)}
                    </div>
                </div>
            </section>

            {/* ── CTA ── */}
            <section className="py-24 px-6 bg-gradient-to-r from-violet-700 via-fuchsia-700 to-pink-600">
                <div className="max-w-3xl mx-auto text-center text-white">
                    <h2 className="text-4xl md:text-5xl font-extrabold mb-4">{t.ctaTitle}</h2>
                    <p className="text-xl text-white/80 mb-10">{t.ctaSubtitle}</p>
                    <Link href={user ? "/dashboard" : "/signup"}>
                        <Button className="h-14 px-12 text-base font-bold rounded-2xl bg-gray-950 text-violet-300 hover:bg-gray-900 shadow-xl shadow-black/30 hover:-translate-y-0.5 transition-all duration-300">
                            {user ? t.ctaBtnUser : t.ctaBtn}
                        </Button>
                    </Link>
                    <p className="text-white/50 text-sm mt-4">{t.ctaNote}</p>
                </div>
            </section>

            {/* ── FOOTER ── */}
            <footer className="bg-gray-900 border-t border-gray-800 text-gray-500 py-12 px-6">
                <div className="max-w-6xl mx-auto">
                    <div className="flex flex-col md:flex-row justify-between items-center gap-6 mb-8">
                        <div className="flex items-center gap-2 font-extrabold text-xl">
                            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-600 to-fuchsia-500 flex items-center justify-center text-white font-bold">L</div>
                            <span className="text-white">LearnAble</span>
                        </div>
                        <div className="flex gap-6 text-sm">
                            <Link href="/assessment/dyslexia" className="hover:text-white transition-colors">Assessment</Link>
                            <Link href="/dashboard"           className="hover:text-white transition-colors">Dashboard</Link>
                            <Link href="/report"              className="hover:text-white transition-colors">Report</Link>
                            <Link href="/specialists"         className="hover:text-white transition-colors">Find Specialists</Link>
                            <Link href="/parent"              className="hover:text-white transition-colors">For Parents</Link>
                        </div>
                    </div>
                    <div className="border-t border-gray-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs">
                        <p>© {new Date().getFullYear()} LearnAble. {t.footerNote}</p>
                        {/* Footer language switcher */}
                        <div className="flex items-center gap-3">
                            <LangSwitcher lang={lang} setLang={setLang} />
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    );
}