// "use client";

// import Link from "next/link";
// import { Button } from "@/components/ui/Button";
// import { useAuth } from "@/context/AuthContext";
// import { useState, useEffect, useRef } from "react";

// const GROQ_API_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;

// // ─── Types ────────────────────────────────────────────────────────────────────
// interface AITestimonial {
//     quote: string;
//     name: string;
//     role: string;
//     avatar: string;
// }

// type Lang = "en" | "hi" | "mr";

// // ─── Translations ─────────────────────────────────────────────────────────────
// const T = {
//     en: {
//         nav: { how: "How it Works", features: "Features", stories: "Stories", login: "Log in", signup: "Get Started Free", dashboard: "Dashboard" },
//         badge: "AI-Powered Learning Assessment",
//         heroTop: "Unlock Every Person's",
//         taglineFallback: "Unlock Every Child's Learning Potential",
//         heroDesc: ["LearnAble uses AI to detect", "Dyslexia", "Dysgraphia", "and", "Dyscalculia", "early — then creates a personalised game-based learning path to help them thrive."],
//         startBtn: "🚀 Start Free Assessment",
//         howBtn: "See How it Works ↓",
//         groqTagline: "Tagline generated by Groq AI ⚡",
//         groqStories: "Stories generated by Groq AI ⚡",
//         stats: [
//             { suffix: " Disorders", label: "Covered" },
//             { suffix: "+ games",    label: "Learning Activities" },
//             { suffix: " languages", label: "English, Hindi, Marathi" },
//             { suffix: "% free",     label: "No credit card needed" },
//         ],
//         howTitle: "How it Works",
//         howSubtitle: "Three simple steps from first visit to personalised learning plan.",
//         steps: [
//             { title: "Take the Assessment",  desc: "Three short AI-driven tests cover reading, writing, and maths. Takes less than 15 minutes for all three." },
//             { title: "Get Your Report",      desc: "Instantly receive a professional-grade screening report with risk levels, AI confidence scores, and recommendations." },
//             { title: "Start Learning",       desc: "Jump into a personalised game-based curriculum. XP, streaks, hearts, gems — just like your favourite language app." },
//         ],
//         checklistItems: ["🔍 AI Screening","📊 Detailed Report","🎮 Game-Based Learning","👨‍👩‍👧 Parent Dashboard","🔊 Text-to-Speech","📥 PDF Export (Hindi/Marathi)"],
//         featTitle: "Everything You Need",
//         featSubtitle: "LearnAble is the only platform built specifically for learning disabilities in Indian schools.",
//         features: [
//             { icon: "🧠", title: "AI Diagnosis Engine",     desc: "Neural Network trained on learning patterns detects Dyslexia risk with high accuracy from a 20-question adaptive test.",         accent: "bg-violet-600" },
//             { icon: "✍️", title: "Vision AI (Dysgraphia)", desc: "CNN analyses your child's handwriting pixel-by-pixel to detect motor control issues and letter formation errors.",                accent: "bg-teal-600"   },
//             { icon: "🧮", title: "Dyscalculia Profiler",    desc: "Timed arithmetic, sequencing, and clock-reading tasks mapped against age norms with response time analysis.",                     accent: "bg-orange-500" },
//             { icon: "🎮", title: "10+ Learning Games",      desc: "Phonics, Sight Words, Tracing, Maze Master, Math Race, Shape Sorter — all curriculum-aligned and gamified.",                      accent: "bg-blue-600"   },
//             { icon: "📊", title: "Rich Reporting",          desc: "Professional multi-section PDF reports with bar charts, radar charts, and confidence gauges — in English, Hindi & Marathi.",       accent: "bg-fuchsia-600"},
//             { icon: "👨‍👩‍👧", title: "Parent Dashboard",   desc: "PIN-protected parent view showing progress charts, session history, and a downloadable report for specialists.",                   accent: "bg-green-600"  },
//         ],
//         testimonialsTitle: "What Families Say",
//         testimonialsSubtitle: "Families across India are using LearnAble to understand their children better.",
//         ctaTitle: "Every Child Learns Differently.",
//         ctaSubtitle: "Find out how your child learns — for free, in 15 minutes.",
//         ctaBtn: "Create Free Account →",
//         ctaBtnUser: "Go to Dashboard →",
//         ctaNote: "No credit card. No email required for assessment.",
//         footerNote: "Made with ❤️ for every child who learns differently.",
//     },
//     hi: {
//         nav: { how: "यह कैसे काम करता है", features: "विशेषताएं", stories: "कहानियां", login: "लॉग इन", signup: "मुफ्त शुरू करें", dashboard: "डैशबोर्ड" },
//         badge: "AI-संचालित शिक्षण मूल्यांकन",
//         heroTop: "हर बच्चे की",
//         taglineFallback: "हर बच्चे की सीखने की क्षमता को उजागर करें",
//         heroDesc: ["LearnAble AI का उपयोग करके", "डिस्लेक्सिया", "डिस्ग्राफिया", "और", "डिस्केल्कुलिया", "का जल्दी पता लगाता है — फिर उनके लिए एक व्यक्तिगत गेम-आधारित शिक्षण पथ बनाता है।"],
//         startBtn: "🚀 मुफ्त मूल्यांकन शुरू करें",
//         howBtn: "यह कैसे काम करता है ↓",
//         groqTagline: "Groq AI द्वारा टैगलाइन ⚡",
//         groqStories: "Groq AI द्वारा कहानियां ⚡",
//         stats: [
//             { suffix: " विकार",   label: "कवर किए गए" },
//             { suffix: "+ गेम्स",  label: "शिक्षण गतिविधियाँ" },
//             { suffix: " भाषाएं",  label: "अंग्रेजी, हिंदी, मराठी" },
//             { suffix: "% मुफ्त",  label: "क्रेडिट कार्ड की जरूरत नहीं" },
//         ],
//         howTitle: "यह कैसे काम करता है",
//         howSubtitle: "पहली विजिट से व्यक्तिगत शिक्षण योजना तक तीन सरल चरण।",
//         steps: [
//             { title: "मूल्यांकन लें",       desc: "तीन छोटे AI-संचालित परीक्षण पढ़ना, लिखना और गणित को कवर करते हैं। तीनों के लिए 15 मिनट से कम।" },
//             { title: "अपनी रिपोर्ट पाएं",  desc: "जोखिम स्तर, AI विश्वास स्कोर और सुझावों के साथ तुरंत एक पेशेवर स्क्रीनिंग रिपोर्ट प्राप्त करें।" },
//             { title: "सीखना शुरू करें",    desc: "एक व्यक्तिगत गेम-आधारित पाठ्यक्रम में कूदें। XP, स्ट्रीक, हार्ट, जेम्स — अपने पसंदीदा भाषा ऐप की तरह।" },
//         ],
//         checklistItems: ["🔍 AI स्क्रीनिंग","📊 विस्तृत रिपोर्ट","🎮 गेम-आधारित शिक्षण","👨‍👩‍👧 अभिभावक डैशबोर्ड","🔊 टेक्स्ट-टू-स्पीच","📥 PDF निर्यात (हिंदी/मराठी)"],
//         featTitle: "आपको जो चाहिए वह सब",
//         featSubtitle: "LearnAble भारतीय स्कूलों में सीखने की अक्षमताओं के लिए विशेष रूप से बना एकमात्र प्लेटफ़ॉर्म है।",
//         features: [
//             { icon: "🧠", title: "AI निदान इंजन",        desc: "सीखने के पैटर्न पर प्रशिक्षित न्यूरल नेटवर्क 20-प्रश्न अनुकूली परीक्षण से डिस्लेक्सिया जोखिम का पता लगाता है।",   accent: "bg-violet-600" },
//             { icon: "✍️", title: "विजन AI (डिस्ग्राफिया)", desc: "CNN आपके बच्चे की हस्तलेखन का पिक्सल-दर-पिक्सल विश्लेषण करता है।",                                              accent: "bg-teal-600"   },
//             { icon: "🧮", title: "डिस्केल्कुलिया प्रोफाइलर", desc: "समयबद्ध अंकगणित, अनुक्रमण और घड़ी-पढ़ने के कार्य आयु मानदंडों के विरुद्ध मैप किए गए।",                        accent: "bg-orange-500" },
//             { icon: "🎮", title: "10+ शिक्षण गेम्स",      desc: "फोनिक्स, साइट वर्ड्स, ट्रेसिंग, मेज़ मास्टर, मैथ रेस — सभी पाठ्यक्रम-संरेखित और गेमिफाइड।",                    accent: "bg-blue-600"   },
//             { icon: "📊", title: "समृद्ध रिपोर्टिंग",      desc: "बार चार्ट, राडार चार्ट और विश्वास गेज के साथ पेशेवर PDF रिपोर्ट — अंग्रेजी, हिंदी और मराठी में।",               accent: "bg-fuchsia-600"},
//             { icon: "👨‍👩‍👧", title: "अभिभावक डैशबोर्ड",  desc: "PIN-संरक्षित अभिभावक दृश्य जो प्रगति चार्ट, सत्र इतिहास और विशेषज्ञों के लिए डाउनलोड करने योग्य रिपोर्ट दिखाता है।", accent: "bg-green-600"  },
//         ],
//         testimonialsTitle: "परिवार क्या कहते हैं",
//         testimonialsSubtitle: "भारत भर के परिवार अपने बच्चों को बेहतर समझने के लिए LearnAble का उपयोग कर रहे हैं।",
//         ctaTitle: "हर बच्चा अलग तरह से सीखता है।",
//         ctaSubtitle: "जानें आपका बच्चा कैसे सीखता है — मुफ्त में, 15 मिनट में।",
//         ctaBtn: "मुफ्त अकाउंट बनाएं →",
//         ctaBtnUser: "डैशबोर्ड पर जाएं →",
//         ctaNote: "कोई क्रेडिट कार्ड नहीं। मूल्यांकन के लिए कोई ईमेल जरूरी नहीं।",
//         footerNote: "हर उस बच्चे के लिए ❤️ के साथ बनाया गया जो अलग तरह से सीखता है।",
//     },
//     mr: {
//         nav: { how: "हे कसे कार्य करते", features: "वैशिष्ट्ये", stories: "कथा", login: "लॉग इन", signup: "मोफत सुरू करा", dashboard: "डॅशबोर्ड" },
//         badge: "AI-चालित शिक्षण मूल्यांकन",
//         heroTop: "प्रत्येक मुलाची",
//         taglineFallback: "प्रत्येक मुलाची शिकण्याची क्षमता उघडा",
//         heroDesc: ["LearnAble AI वापरून", "डिस्लेक्सिया", "डिस्ग्राफिया", "आणि", "डिस्कॅल्क्युलिया", "लवकर शोधते — मग त्यांच्यासाठी वैयक्तिक गेम-आधारित शिकण्याचा मार्ग तयार करते।"],
//         startBtn: "🚀 मोफत मूल्यांकन सुरू करा",
//         howBtn: "हे कसे कार्य करते ↓",
//         groqTagline: "Groq AI ने टॅगलाइन तयार केली ⚡",
//         groqStories: "Groq AI ने कथा तयार केल्या ⚡",
//         stats: [
//             { suffix: " विकार",   label: "समाविष्ट" },
//             { suffix: "+ गेम्स",  label: "शिक्षण क्रियाकलाप" },
//             { suffix: " भाषा",    label: "इंग्रजी, हिंदी, मराठी" },
//             { suffix: "% मोफत",   label: "क्रेडिट कार्ड नको" },
//         ],
//         howTitle: "हे कसे कार्य करते",
//         howSubtitle: "पहिल्या भेटीपासून वैयक्तिक शिक्षण योजनेपर्यंत तीन सोपे टप्पे।",
//         steps: [
//             { title: "मूल्यांकन घ्या",       desc: "तीन छोटे AI-चालित चाचण्या वाचन, लेखन आणि गणित कव्हर करतात. तिन्हींसाठी 15 मिनिटांपेक्षा कमी वेळ लागतो." },
//             { title: "तुमचा अहवाल मिळवा",   desc: "जोखीम पातळी, AI विश्वास स्कोअर आणि शिफारशींसह त्वरित व्यावसायिक स्क्रीनिंग अहवाल मिळवा." },
//             { title: "शिकणे सुरू करा",       desc: "वैयक्तिक गेम-आधारित अभ्यासक्रमात प्रवेश करा. XP, स्ट्रीक, हार्ट, जेम्स — आपल्या आवडत्या भाषा अॅपसारखे." },
//         ],
//         checklistItems: ["🔍 AI स्क्रीनिंग","📊 तपशीलवार अहवाल","🎮 गेम-आधारित शिक्षण","👨‍👩‍👧 पालक डॅशबोर्ड","🔊 मजकूर-ते-भाषण","📥 PDF निर्यात (हिंदी/मराठी)"],
//         featTitle: "तुम्हाला जे हवे ते सर्व",
//         featSubtitle: "LearnAble हे भारतीय शाळांमधील शिकण्याच्या अक्षमतांसाठी विशेषतः बनवलेले एकमेव व्यासपीठ आहे।",
//         features: [
//             { icon: "🧠", title: "AI निदान इंजिन",         desc: "शिकण्याच्या नमुन्यांवर प्रशिक्षित न्यूरल नेटवर्क 20-प्रश्न चाचणीतून डिस्लेक्सिया जोखीम शोधते.",             accent: "bg-violet-600" },
//             { icon: "✍️", title: "व्हिजन AI (डिस्ग्राफिया)", desc: "CNN तुमच्या मुलाच्या हस्ताक्षराचे पिक्सेल-दर-पिक्सेल विश्लेषण करते.",                                    accent: "bg-teal-600"   },
//             { icon: "🧮", title: "डिस्कॅल्क्युलिया प्रोफाइलर", desc: "वयोमानानुसार मानदंडांविरुद्ध कालबद्ध अंकगणित, अनुक्रम आणि घड्याळ-वाचन कार्ये.",                        accent: "bg-orange-500" },
//             { icon: "🎮", title: "10+ शिक्षण गेम्स",        desc: "फोनिक्स, साइट वर्ड्स, ट्रेसिंग, मेज मास्टर, मॅथ रेस — सर्व अभ्यासक्रम-संरेखित आणि गेमिफाइड.",            accent: "bg-blue-600"   },
//             { icon: "📊", title: "समृद्ध अहवाल",            desc: "बार चार्ट, रडार चार्ट आणि विश्वास गेजसह व्यावसायिक PDF अहवाल — इंग्रजी, हिंदी आणि मराठीत.",               accent: "bg-fuchsia-600"},
//             { icon: "👨‍👩‍👧", title: "पालक डॅशबोर्ड",     desc: "PIN-संरक्षित पालक दृश्य जे प्रगती चार्ट, सत्र इतिहास आणि डाउनलोड करण्यायोग्य अहवाल दाखवते.",              accent: "bg-green-600"  },
//         ],
//         testimonialsTitle: "कुटुंबे काय म्हणतात",
//         testimonialsSubtitle: "भारतभरातील कुटुंबे त्यांच्या मुलांना अधिक चांगल्या प्रकारे समजून घेण्यासाठी LearnAble वापरत आहेत.",
//         ctaTitle: "प्रत्येक मूल वेगळ्या प्रकारे शिकते.",
//         ctaSubtitle: "तुमचे मूल कसे शिकते ते जाणून घ्या — मोफत, 15 मिनिटांत.",
//         ctaBtn: "मोफत खाते तयार करा →",
//         ctaBtnUser: "डॅशबोर्डवर जा →",
//         ctaNote: "क्रेडिट कार्ड नाही. मूल्यांकनासाठी ईमेल आवश्यक नाही.",
//         footerNote: "वेगळ्या प्रकारे शिकणाऱ्या प्रत्येक मुलासाठी ❤️ ने बनवले.",
//     },
// };

// // ─── Fallback testimonials ────────────────────────────────────────────────────
// const FALLBACK_TESTIMONIALS: AITestimonial[] = [
//     { quote: "My son struggled to read for years. After the assessment, we finally had a name for it — and a plan. The Phonics game is his favourite part of the day now.", name: "Priya Sharma",        role: "Mother of a 9-year-old, Pune",  avatar: "priya"     },
//     { quote: "The report we downloaded in Marathi was something we could finally share with my mother-in-law. She understood exactly what her granddaughter needs.",         name: "Aishwarya Kulkarni", role: "Parent, Nashik",                avatar: "aishwarya" },
//     { quote: "As a special educator, I recommend LearnAble to every school I work with. The AI confidence scores help me start conversations with parents.",                 name: "Mr. Ramesh Patil",   role: "Special Educator, Mumbai",      avatar: "ramesh"    },
// ];

// // ─── Groq helpers ─────────────────────────────────────────────────────────────
// async function fetchAITagline(): Promise<string> {
//     const themes = ["hope and discovery","every child is unique","unlocking hidden strengths","seeing the world differently","early support changes everything"];
//     const theme = themes[Math.floor(Math.random() * themes.length)];
//     const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
//         method: "POST",
//         headers: { "Content-Type": "application/json", Authorization: `Bearer ${GROQ_API_KEY}` },
//         body: JSON.stringify({
//             model: "llama-3.3-70b-versatile",
//             messages: [
//                 { role: "system", content: "You write punchy 6–10 word hero taglines for an AI learning disability platform for Indian families. Return ONLY the tagline text — no quotes, no punctuation at the end, no explanation." },
//                 { role: "user", content: `Write a warm, inspiring tagline with the theme: "${theme}". Max 10 words.` },
//             ],
//             temperature: 1.1, max_tokens: 30,
//         }),
//     });
//     if (!res.ok) throw new Error("Groq tagline error");
//     const data = await res.json();
//     return data?.choices?.[0]?.message?.content?.trim() || "Unlock Every Child's Learning Potential";
// }

// async function fetchAITestimonials(): Promise<AITestimonial[]> {
//     const seed = Math.random().toString(36).slice(2, 7);
//     const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
//         method: "POST",
//         headers: { "Content-Type": "application/json", Authorization: `Bearer ${GROQ_API_KEY}` },
//         body: JSON.stringify({
//             model: "llama-3.3-70b-versatile",
//             messages: [
//                 { role: "system", content: "You generate realistic testimonials for an AI learning disability assessment platform for Indian families. Return ONLY raw JSON — no markdown, no code fences." },
//                 { role: "user", content: `Seed: ${seed}. Generate 3 testimonials from Indian parents or educators. Each from a different Indian city. Return JSON array: [{"quote":"...","name":"...","role":"...","avatar":"seed_word"}]. Quotes 2 sentences, warm and specific. Real Indian names.` },
//             ],
//             temperature: 1.0, max_tokens: 600,
//         }),
//     });
//     if (!res.ok) throw new Error("Groq testimonials error");
//     const data = await res.json();
//     const raw = data?.choices?.[0]?.message?.content || "[]";
//     try {
//         const fence = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
//         const clean = fence ? fence[1] : raw;
//         const arr = clean.match(/\[[\s\S]*\]/);
//         return arr ? JSON.parse(arr[0]) : [];
//     } catch { return []; }
// }

// // ─── Animated counter ─────────────────────────────────────────────────────────
// function Counter({ target, suffix = "" }: { target: number; suffix?: string }) {
//     const [val, setVal] = useState(0);
//     useEffect(() => {
//         let start = 0;
//         const step = Math.ceil(target / 60);
//         const timer = setInterval(() => {
//             start += step;
//             if (start >= target) { setVal(target); clearInterval(timer); } else setVal(start);
//         }, 20);
//         return () => clearInterval(timer);
//     }, [target]);
//     return <>{val.toLocaleString()}{suffix}</>;
// }

// // ─── Feature card ─────────────────────────────────────────────────────────────
// function FeatureCard({ icon, title, desc, accent }: { icon: string; title: string; desc: string; accent: string }) {
//     return (
//         <div className="group relative p-6 rounded-2xl border border-gray-700 bg-gray-800/60 shadow-lg shadow-yellow-500/40 hover:shadow-xl hover:shadow-yellow-400/60 hover:-translate-y-1 transition-all duration-300 overflow-hidden backdrop-blur-sm">
//             <div className={`absolute inset-0 opacity-0 group-hover:opacity-10 transition-opacity duration-300 ${accent}`} />
//             <div className="text-4xl mb-4">{icon}</div>
//             <h3 className="font-bold text-lg text-white mb-2">{title}</h3>
//             <p className="text-gray-400 text-sm leading-relaxed">{desc}</p>
//         </div>
//     );
// }

// // ─── Step card ────────────────────────────────────────────────────────────────
// function Step({ n, title, desc, color }: { n: string; title: string; desc: string; color: string }) {
//     return (
//         <div className="flex gap-5">
//             <div className={`w-12 h-12 rounded-full ${color} text-white font-bold text-lg flex items-center justify-center shrink-0 shadow-lg`}>{n}</div>
//             <div>
//                 <h4 className="font-bold text-white mb-1">{title}</h4>
//                 <p className="text-gray-400 text-sm leading-relaxed">{desc}</p>
//             </div>
//         </div>
//     );
// }

// // ─── Testimonial card ─────────────────────────────────────────────────────────
// function TestimonialCard({ quote, name, role, avatar }: AITestimonial) {
//     return (
//         <div className="bg-gray-800/70 rounded-2xl p-6 shadow-lg shadow-green-700/50 border border-gray-700 h-full flex flex-col justify-between backdrop-blur-sm">
//             <p className="text-gray-300 text-sm leading-relaxed mb-5">&ldquo;{quote}&rdquo;</p>
//             <div className="flex items-center gap-3">
//                 <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${avatar}`} alt={name} className="w-10 h-10 rounded-full bg-violet-900" />
//                 <div>
//                     <p className="font-semibold text-white text-sm">{name}</p>
//                     <p className="text-gray-500 text-xs">{role}</p>
//                 </div>
//             </div>
//         </div>
//     );
// }

// // ─── Skeleton loader ──────────────────────────────────────────────────────────
// function TestimonialSkeleton() {
//     return (
//         <div className="bg-gray-800/70 rounded-2xl p-6 border border-gray-700 animate-pulse">
//             <div className="h-3 bg-gray-700 rounded mb-2 w-full" />
//             <div className="h-3 bg-gray-700 rounded mb-2 w-4/5" />
//             <div className="h-3 bg-gray-700 rounded mb-5 w-3/5" />
//             <div className="flex items-center gap-3">
//                 <div className="w-10 h-10 rounded-full bg-gray-700" />
//                 <div className="space-y-1.5">
//                     <div className="h-3 bg-gray-700 rounded w-24" />
//                     <div className="h-2.5 bg-gray-700 rounded w-32" />
//                 </div>
//             </div>
//         </div>
//     );
// }

// // ─── Pill ─────────────────────────────────────────────────────────────────────
// function Pill({ label, color }: { label: string; color: string }) {
//     return <span className={`px-3 py-1 rounded-full text-xs font-bold ${color}`}>{label}</span>;
// }

// // ─── Language Switcher ────────────────────────────────────────────────────────
// function LangSwitcher({ lang, setLang }: { lang: Lang; setLang: (l: Lang) => void }) {
//     const langs: { code: Lang; label: string }[] = [
//         { code: "en", label: "EN" },
//         { code: "hi", label: "हि" },
//         { code: "mr", label: "म" },
//     ];
//     return (
//         <div className="flex items-center gap-1 bg-gray-800 border border-gray-700 rounded-full px-1 py-1">
//             {langs.map(({ code, label }) => (
//                 <button
//                     key={code}
//                     onClick={() => setLang(code)}
//                     className={`px-3 py-1 rounded-full text-xs font-bold transition-all duration-200 ${
//                         lang === code
//                             ? "bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white shadow-md"
//                             : "text-gray-400 hover:text-white"
//                     }`}
//                 >
//                     {label}
//                 </button>
//             ))}
//         </div>
//     );
// }

// // ─── Main Page ────────────────────────────────────────────────────────────────
// export default function Home() {
//     const { user } = useAuth();

//     const [lang, setLang] = useState<Lang>("en");
//     const t = T[lang];

//     const [aiTagline, setAiTagline] = useState<string>("");
//     const [taglineLoading, setTaglineLoading] = useState(true);
//     const [testimonials, setTestimonials] = useState<AITestimonial[]>([]);
//     const [testimonialsLoading, setTestimonialsLoading] = useState(true);
//     const hasFetched = useRef(false);

//     useEffect(() => {
//         if (hasFetched.current) return;
//         hasFetched.current = true;
//         fetchAITagline()
//             .then((t) => setAiTagline(t))
//             .catch(() => setAiTagline(""))
//             .finally(() => setTaglineLoading(false));
//         fetchAITestimonials()
//             .then((t) => setTestimonials(t.length ? t : FALLBACK_TESTIMONIALS))
//             .catch(() => setTestimonials(FALLBACK_TESTIMONIALS))
//             .finally(() => setTestimonialsLoading(false));
//     }, []);

//     const displayTagline = aiTagline || t.taglineFallback;

//     return (
//         <div className="min-h-screen bg-gray-950 font-sans">

//             {/* ── NAV ── */}
//             <nav className="sticky top-0 z-50 bg-gray-900/80 backdrop-blur-md border-b border-gray-800 shadow-sm">
//                 <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
//                     <div className="flex items-center gap-2 font-extrabold text-xl">
//                         <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-600 to-fuchsia-500 flex items-center justify-center text-white font-bold shadow-md">L</div>
//                         <span className="bg-clip-text text-transparent bg-gradient-to-r from-violet-400 to-fuchsia-400">LearnAble</span>
//                     </div>
//                     <div className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-400">
//                         <a href="#how"          className="hover:text-violet-400 transition-colors">{t.nav.how}</a>
//                         <a href="#features"     className="hover:text-violet-400 transition-colors">{t.nav.features}</a>
//                         <a href="#testimonials" className="hover:text-violet-400 transition-colors">{t.nav.stories}</a>
//                     </div>
//                     <div className="flex items-center gap-3">
//                         {/* ── Language Switcher ── */}
//                         <LangSwitcher lang={lang} setLang={setLang} />

//                         {user ? (
//                             <div className="flex items-center gap-3">
//                                 <Link href="/dashboard">
//                                     <Button className="rounded-full px-5 py-2 bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white text-sm font-semibold shadow-md hover:shadow-violet-700 transition-all">
//                                         {t.nav.dashboard}
//                                     </Button>
//                                 </Link>
//                                 <Link href="/profile">
//                                     <div className="flex items-center gap-2 bg-gray-800 hover:bg-gray-700 px-3 py-1.5 rounded-full cursor-pointer transition-all border border-gray-700">
//                                         <img src={user.profileImage || `https://api.dicebear.com/7.x/avataaars/svg?seed=${user.name}`} alt="Profile" className="w-7 h-7 rounded-full" />
//                                         <span className="text-sm font-medium text-gray-200 max-w-[100px] truncate">{user.name}</span>
//                                     </div>
//                                 </Link>
//                             </div>
//                         ) : (
//                             <>
//                                 <Link href="/login" className="text-sm font-medium text-gray-400 hover:text-violet-400 transition-colors">{t.nav.login}</Link>
//                                 <Link href="/signup">
//                                     <Button className="rounded-full px-5 py-2 bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white text-sm font-semibold shadow-md hover:shadow-violet-700 transition-all">
//                                         {t.nav.signup}
//                                     </Button>
//                                 </Link>
//                             </>
//                         )}
//                     </div>
//                 </div>
//             </nav>

//             {/* ── HERO ── */}
//             <section className="relative overflow-hidden pt-24 pb-32 px-6">
//                 <div className="absolute -top-24 -left-24 w-[500px] h-[500px] bg-violet-900 rounded-full blur-[120px] opacity-30 pointer-events-none" />
//                 <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-fuchsia-900 rounded-full blur-[120px] opacity-25 pointer-events-none" />
//                 <div className="absolute bottom-0 left-1/2 w-[300px] h-[300px] bg-blue-900 rounded-full blur-[100px] opacity-20 pointer-events-none" />

//                 <div className="max-w-5xl mx-auto text-center relative z-10">
//                     <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-violet-900/60 border border-violet-700 text-violet-300 text-sm font-semibold mb-8 shadow-sm">
//                         <span className="w-2 h-2 rounded-full bg-violet-400 animate-pulse" />
//                         {t.badge}
//                     </div>

//                     <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 leading-tight">
//                         <span className="text-gray-100">{t.heroTop}</span><br />
//                         {taglineLoading ? (
//                             <span className="inline-block bg-gray-800 animate-pulse rounded-xl h-16 w-96 align-middle" />
//                         ) : (
//                             <span className="bg-clip-text text-transparent bg-gradient-to-r from-violet-400 via-fuchsia-400 to-pink-400">
//                                 {displayTagline}
//                             </span>
//                         )}
//                     </h1>

//                     {!taglineLoading && (
//                         <div className="inline-flex items-center gap-1.5 text-xs text-gray-500 mb-3">
//                             <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
//                             {t.groqTagline}
//                         </div>
//                     )}

//                     <p className="text-lg md:text-xl text-gray-400 max-w-2xl mx-auto mb-10 leading-relaxed">
//                         {t.heroDesc[0]}{" "}
//                         <strong className="text-gray-200">{t.heroDesc[1]}</strong>,{" "}
//                         <strong className="text-gray-200">{t.heroDesc[2]}</strong>{" "}
//                         {t.heroDesc[3]}{" "}
//                         <strong className="text-gray-200">{t.heroDesc[4]}</strong>{" "}
//                         {t.heroDesc[5]}
//                     </p>

//                     <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
//                         <Link href="/assessment/dyslexia">
//                             <Button className="h-14 px-10 text-base font-bold rounded-2xl bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white shadow-xl shadow-violet-900/50 hover:shadow-violet-700 hover:-translate-y-0.5 transition-all duration-300">
//                                 {t.startBtn}
//                             </Button>
//                         </Link>
//                         <a href="#how">
//                             <Button variant="secondary" className="h-14 px-10 text-base font-semibold rounded-2xl border-2 border-gray-700 bg-gray-800/60 text-gray-300 hover:border-violet-600 hover:text-violet-300 transition-all duration-300">
//                                 {t.howBtn}
//                             </Button>
//                         </a>
//                     </div>

//                     <div className="flex flex-wrap justify-center gap-3">
//                         <Pill label="📖 Dyslexia"         color="bg-violet-900/60 text-violet-300 border border-violet-700" />
//                         <Pill label="✍️ Dysgraphia"       color="bg-teal-900/60 text-teal-300 border border-teal-700" />
//                         <Pill label="🧮 Dyscalculia"      color="bg-orange-900/60 text-orange-300 border border-orange-700" />
//                         <Pill label="🧠 AI Powered"       color="bg-blue-900/60 text-blue-300 border border-blue-700" />
//                         <Pill label="🇮🇳 Hindi & Marathi"  color="bg-green-900/60 text-green-300 border border-green-700" />
//                     </div>
//                 </div>
//             </section>

//             {/* ── STATS ── */}
//             <section className="bg-gray-900 border-y border-gray-800 py-14 px-6">
//                 <div className="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
//                     {[3, 20, 3, 100].map((val, i) => (
//                         <div key={i}>
//                             <p className="text-4xl font-extrabold text-violet-400 mb-1">
//                                 <Counter target={val} suffix={t.stats[i].suffix} />
//                             </p>
//                             <p className="text-sm text-gray-500">{t.stats[i].label}</p>
//                         </div>
//                     ))}
//                 </div>
//             </section>

//             {/* ── HOW IT WORKS ── */}
//             <section id="how" className="py-24 px-6 bg-gray-950">
//                 <div className="max-w-4xl mx-auto">
//                     <h2 className="text-3xl md:text-4xl font-extrabold text-white text-center mb-4">{t.howTitle}</h2>
//                     <p className="text-center text-gray-500 mb-16 max-w-xl mx-auto">{t.howSubtitle}</p>
//                     <div className="grid md:grid-cols-2 gap-12 items-center">
//                         <div className="space-y-8">
//                             <Step n="1" title={t.steps[0].title} desc={t.steps[0].desc} color="bg-violet-600" />
//                             <Step n="2" title={t.steps[1].title} desc={t.steps[1].desc} color="bg-fuchsia-500" />
//                             <Step n="3" title={t.steps[2].title} desc={t.steps[2].desc} color="bg-orange-500" />
//                         </div>
//                         <div className="bg-gradient-to-br from-violet-700 to-fuchsia-600 rounded-3xl p-8 text-white shadow-2xl shadow-violet-900/50">
//                             <div className="space-y-4">
//                                 {t.checklistItems.map((f, i) => (
//                                     <div key={i} className="flex items-center gap-3">
//                                         <div className="w-5 h-5 rounded-full bg-white/20 flex items-center justify-center text-xs">✓</div>
//                                         <span className="text-white/90 text-sm font-medium">{f}</span>
//                                     </div>
//                                 ))}
//                             </div>
//                         </div>
//                     </div>
//                 </div>
//             </section>

//             {/* ── FEATURES ── */}
//             <section id="features" className="bg-gray-900 py-24 px-6">
//                 <div className="max-w-6xl mx-auto">
//                     <h2 className="text-3xl md:text-4xl font-extrabold text-white text-center mb-4">{t.featTitle}</h2>
//                     <p className="text-center text-gray-500 mb-16 max-w-xl mx-auto">{t.featSubtitle}</p>
//                     <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
//                         {t.features.map((f, i) => <FeatureCard key={i} {...f} />)}
//                     </div>
//                 </div>
//             </section>

//             {/* ── TESTIMONIALS ── */}
//             <section id="testimonials" className="py-24 px-6 bg-gray-950 shadow-lg shadow-green-700">
//                 <div className="max-w-5xl mx-auto">
//                     <div className="text-center mb-4">
//                         <h2 className="text-3xl md:text-4xl font-extrabold text-white mb-2">{t.testimonialsTitle}</h2>
//                         {!testimonialsLoading && (
//                             <span className="inline-flex items-center gap-1.5 text-xs text-gray-500">
//                                 <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
//                                 {t.groqStories}
//                             </span>
//                         )}
//                     </div>
//                     <p className="text-center text-gray-500 mb-16 max-w-xl mx-auto">{t.testimonialsSubtitle}</p>
//                     <div className="grid md:grid-cols-3 gap-6">
//                         {testimonialsLoading
//                             ? [1, 2, 3].map((i) => <TestimonialSkeleton key={i} />)
//                             : testimonials.map((t, i) => <TestimonialCard key={i} {...t} />)}
//                     </div>
//                 </div>
//             </section>

//             {/* ── CTA ── */}
//             <section className="py-24 px-6 bg-gradient-to-r from-violet-700 via-fuchsia-700 to-pink-600">
//                 <div className="max-w-3xl mx-auto text-center text-white">
//                     <h2 className="text-4xl md:text-5xl font-extrabold mb-4">{t.ctaTitle}</h2>
//                     <p className="text-xl text-white/80 mb-10">{t.ctaSubtitle}</p>
//                     <Link href={user ? "/dashboard" : "/signup"}>
//                         <Button className="h-14 px-12 text-base font-bold rounded-2xl bg-gray-950 text-violet-300 hover:bg-gray-900 shadow-xl shadow-black/30 hover:-translate-y-0.5 transition-all duration-300">
//                             {user ? t.ctaBtnUser : t.ctaBtn}
//                         </Button>
//                     </Link>
//                     <p className="text-white/50 text-sm mt-4">{t.ctaNote}</p>
//                 </div>
//             </section>

//             {/* ── FOOTER ── */}
//             <footer className="bg-gray-900 border-t border-gray-800 text-gray-500 py-12 px-6">
//                 <div className="max-w-6xl mx-auto">
//                     <div className="flex flex-col md:flex-row justify-between items-center gap-6 mb-8">
//                         <div className="flex items-center gap-2 font-extrabold text-xl">
//                             <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-600 to-fuchsia-500 flex items-center justify-center text-white font-bold">L</div>
//                             <span className="text-white">LearnAble</span>
//                         </div>
//                         <div className="flex gap-6 text-sm">
//                             <Link href="/assessment/dyslexia" className="hover:text-white transition-colors">Assessment</Link>
//                             <Link href="/dashboard"           className="hover:text-white transition-colors">Dashboard</Link>
//                             <Link href="/report"              className="hover:text-white transition-colors">Report</Link>
//                             <Link href="/specialists"         className="hover:text-white transition-colors">Find Specialists</Link>
//                             <Link href="/parent"              className="hover:text-white transition-colors">For Parents</Link>
//                         </div>
//                     </div>
//                     <div className="border-t border-gray-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs">
//                         <p>© {new Date().getFullYear()} LearnAble. {t.footerNote}</p>
//                         {/* Footer language switcher */}
//                         <div className="flex items-center gap-3">
//                             <LangSwitcher lang={lang} setLang={setLang} />
//                         </div>
//                     </div>
//                 </div>
//             </footer>
//         </div>
//     );
// }

"use client";

import Link from "next/link";
import { useAuth } from "@/context/AuthContext";
import { useState, useEffect, useRef } from "react";

// ─── Types ────────────────────────────────────────────────────────────────────
type Lang = "en" | "hi" | "mr";

// ─── Translations (Intact) ────────────────────────────────────────────────────
const T = {
  en: {
    nav: { how: "How it Works", features: "Features", stories: "Stories", login: "Log in", signup: "Get Started Free", dashboard: "Dashboard" },
    badge: "AI-Powered · Free · Built for India",
    heroLine1: "Every Person Deserves",
    heroLine2: "to Be Understood.",
    heroSub: "LearnAble screens for Dyslexia, Dysgraphia & Dyscalculia through fun games — then builds a personalised learning path. Free. In 15 minutes.",
    startBtn: "Start Free Assessment",
    howBtn: "See How it Works",
    statsItems: [
      { n: "3", label: "Disabilities Screened" },
      { n: "10+", label: "Learning Games" },
      { n: "3", label: "Languages" },
      { n: "100%", label: "Free Forever" },
    ],
    disabilityTitle: "What We Screen For",
    disabilities: [
      {
        id: "dyslexia", color: "#7c3aed", bg: "#f5f3ff",
        icon: "📖", title: "Dyslexia",
        tagline: "Reading & Spelling",
        desc: "Difficulty recognising words, spelling, and decoding text. Affects 1 in 10 children.",
        signals: ["Letter reversals", "Slow reading", "Phonics confusion"],
        cta: "Take Dyslexia Test", href: "/assessment/dyslexia",
      },
      {
        id: "dysgraphia", color: "#0d9488", bg: "#f0fdfa",
        icon: "✍️", title: "Dysgraphia",
        tagline: "Writing & Motor Skills",
        desc: "Trouble with handwriting, spacing, and putting thoughts on paper despite knowing the content.",
        signals: ["Inconsistent letter size", "Poor pencil grip", "Slow writing"],
        cta: "Take Dysgraphia Test", href: "/assessment/dysgraphia",
      },
      {
        id: "dyscalculia", color: "#ea580c", bg: "#fff7ed",
        icon: "🔢", title: "Dyscalculia",
        tagline: "Numbers & Math",
        desc: "Difficulty understanding numbers, arithmetic, and mathematical concepts — not about intelligence.",
        signals: ["Counting on fingers", "Struggles with time", "Number reversals"],
        cta: "Take Dyscalculia Test", href: "/assessment/dyscalculia",
      },
    ],
    howTitle: "Three Steps. Fifteen Minutes.",
    steps: [
      { n: "01", title: "Play the Games", desc: "Adaptive AI-driven games test reading, writing, and maths skills — designed to feel fun, not clinical.", icon: "🎮" },
      { n: "02", title: "Get Your Report", desc: "Receive a detailed screening report with risk levels, confidence scores, and specific flags per category.", icon: "📊" },
      { n: "03", title: "Start Learning", desc: "Jump into personalised game-based learning paths. Earn XP, maintain streaks, unlock new levels.", icon: "🚀" },
    ],
    featTitle: "Built Different.",
    featSub: "Not another generic quiz. Every feature is designed around how Person with learning differences actually think.",
    features: [
      { icon: "🧠", title: "Evidence-Based Engine", desc: "Screening logic built on published rubrics — DST, WRAT, Connelly 2006. Not guesswork." },
      { icon: "🦉", title: "Owly AI Tutor", desc: "A Groq-powered LLaMA 3.3 70B chatbot tuned for child-friendly encouragement and learning support." },
      { icon: "📥", title: "PDF Reports in Hindi & Marathi", desc: "Download professional reports in English, Hindi, or Marathi to share with teachers and specialists." },
      { icon: "👨‍👩‍👧", title: "Parent Dashboard", desc: "PIN-protected parent view with progress charts, session history, and specialist referral support." },
      { icon: "🔊", title: "Text-to-Speech", desc: "Every question can be read aloud — removing the reading barrier for Person who need it most." },
      { icon: "🔒", title: "100% Private", desc: "All data stays in your browser. No server. No account needed to take assessments." },
    ],
    testimonialsTitle: "What Families Say",
    testimonials: [
      { quote: "My son struggled to read for years. After the assessment, we finally had a name for it — and a plan. The Phonics game is his favourite part of the day now.", name: "Priya Sharma", role: "Mother of a 9-year-old, Pune", seed: "priya" },
      { quote: "The report we downloaded in Marathi was something we could finally share with my mother-in-law. She understood exactly what her granddaughter needs.", name: "Aishwarya Kulkarni", role: "Parent, Nashik", seed: "aishwarya" },
      { quote: "As a special educator, I recommend LearnAble to every school I work with. The AI confidence scores help me start conversations with parents.", name: "Mr. Ramesh Patil", role: "Special Educator, Mumbai", seed: "ramesh" },
    ],
    ctaTitle: "Your child's potential is waiting.",
    ctaSub: "Free screening. No credit card. No account required to start.",
    ctaBtn: "Begin Free Assessment →",
    ctaBtnUser: "Go to Dashboard →",
    footerNote: "Made with ❤️ for every child who learns differently.",
  },
  hi: {
    nav: { how: "कैसे काम करता है", features: "विशेषताएं", stories: "कहानियां", login: "लॉग इन", signup: "मुफ्त शुरू करें", dashboard: "डैशबोर्ड" },
    badge: "AI-संचालित · मुफ्त · भारत के लिए",
    heroLine1: "हर बच्चे को",
    heroLine2: "समझा जाना चाहिए।",
    heroSub: "LearnAble मज़ेदार खेलों के ज़रिए डिस्लेक्सिया, डिस्ग्राफिया और डिस्केल्कुलिया की स्क्रीनिंग करता है — फिर एक व्यक्तिगत सीखने का रास्ता बनाता है। मुफ्त। 15 मिनट में।",
    startBtn: "मुफ्त मूल्यांकन शुरू करें",
    howBtn: "यह कैसे काम करता है",
    statsItems: [
      { n: "3", label: "विकार स्क्रीन किए" },
      { n: "10+", label: "शिक्षण खेल" },
      { n: "3", label: "भाषाएं" },
      { n: "100%", label: "हमेशा मुफ्त" },
    ],
    disabilityTitle: "हम क्या स्क्रीन करते हैं",
    disabilities: [
      { id: "dyslexia", color: "#7c3aed", bg: "#f5f3ff", icon: "📖", title: "डिस्लेक्सिया", tagline: "पढ़ना और वर्तनी", desc: "शब्दों को पहचानने, वर्तनी और पाठ को समझने में कठिनाई। 10 में से 1 बच्चे को प्रभावित करता है।", signals: ["अक्षर उलटना", "धीमा पढ़ना", "फोनिक्स भ्रम"], cta: "डिस्लेक्सिया टेस्ट लें", href: "/assessment/dyslexia" },
      { id: "dysgraphia", color: "#0d9488", bg: "#f0fdfa", icon: "✍️", title: "डिस्ग्राफिया", tagline: "लेखन और मोटर कौशल", desc: "हस्तलेखन, रिक्ति और कागज पर विचारों को रखने में परेशानी।", signals: ["असंगत अक्षर आकार", "कमज़ोर पेंसिल पकड़", "धीमा लेखन"], cta: "डिस्ग्राफिया टेस्ट लें", href: "/assessment/dysgraphia" },
      { id: "dyscalculia", color: "#ea580c", bg: "#fff7ed", icon: "🔢", title: "डिस्केल्कुलिया", tagline: "संख्याएं और गणित", desc: "संख्याओं और गणित को समझने में कठिनाई — यह बुद्धि के बारे में नहीं है।", signals: ["उंगलियों पर गिनना", "समय के साथ संघर्ष", "संख्या उलटना"], cta: "डिस्केल्कुलिया टेस्ट लें", href: "/assessment/dyscalculia" },
    ],
    howTitle: "तीन चरण। पंद्रह मिनट।",
    steps: [
      { n: "01", title: "खेल खेलें", desc: "अनुकूली AI-संचालित खेल पढ़ने, लिखने और गणित कौशल का परीक्षण करते हैं।", icon: "🎮" },
      { n: "02", title: "अपनी रिपोर्ट पाएं", desc: "जोखिम स्तर, विश्वास स्कोर के साथ विस्तृत स्क्रीनिंग रिपोर्ट प्राप्त करें।", icon: "📊" },
      { n: "03", title: "सीखना शुरू करें", desc: "व्यक्तिगत गेम-आधारित सीखने के रास्तों में कूदें। XP अर्जित करें, स्ट्रीक बनाए रखें।", icon: "🚀" },
    ],
    featTitle: "अलग तरह से बनाया गया।",
    featSub: "कोई साधारण क्विज़ नहीं। हर सुविधा इस बात के आधार पर डिज़ाइन की गई है कि सीखने में अंतर वाले बच्चे वास्तव में कैसे सोचते हैं।",
    features: [
      { icon: "🧠", title: "साक्ष्य-आधारित इंजन", desc: "प्रकाशित रूब्रिक्स पर आधारित स्क्रीनिंग — अनुमान नहीं।" },
      { icon: "🦉", title: "Owly AI ट्यूटर", desc: "Groq-संचालित LLaMA 3.3 70B चैटबॉट।" },
      { icon: "📥", title: "हिंदी और मराठी में PDF रिपोर्ट", desc: "अंग्रेजी, हिंदी, या मराठी में पेशेवर रिपोर्ट डाउनलोड करें।" },
      { icon: "👨‍👩‍👧", title: "अभिभावक डैशबोर्ड", desc: "प्रगति चार्ट के साथ PIN-संरक्षित दृश्य।" },
      { icon: "🔊", title: "टेक्स्ट-टू-स्पीच", desc: "हर प्रश्न जोर से पढ़ा जा सकता है।" },
      { icon: "🔒", title: "100% निजी", desc: "सभी डेटा आपके ब्राउज़र में रहता है। कोई सर्वर नहीं।" },
    ],
    testimonialsTitle: "परिवार क्या कहते हैं",
    testimonials: [
      { quote: "मेरे बेटे को सालों से पढ़ने में संघर्ष था। मूल्यांकन के बाद, हमें आखिरकार इसका नाम मिल गया — और एक योजना।", name: "प्रिया शर्मा", role: "9 साल के बच्चे की माँ, पुणे", seed: "priya" },
      { quote: "मराठी में डाउनलोड की गई रिपोर्ट हम आखिरकार अपनी सास के साथ साझा कर सके।", name: "ऐश्वर्या कुलकर्णी", role: "अभिभावक, नाशिक", seed: "aishwarya" },
      { quote: "एक विशेष शिक्षक के रूप में, मैं LearnAble को हर उस स्कूल को सुझाता हूं जिसके साथ मैं काम करता हूं।", name: "श्री रमेश पाटिल", role: "विशेष शिक्षक, मुंबई", seed: "ramesh" },
    ],
    ctaTitle: "आपके बच्चे की क्षमता इंतजार कर रही है।",
    ctaSub: "मुफ्त स्क्रीनिंग। कोई क्रेडिट कार्ड नहीं। शुरू करने के लिए कोई खाता नहीं चाहिए।",
    ctaBtn: "मुफ्त मूल्यांकन शुरू करें →",
    ctaBtnUser: "डैशबोर्ड पर जाएं →",
    footerNote: "हर उस बच्चे के लिए ❤️ के साथ बनाया गया जो अलग तरह से सीखता है।",
  },
  mr: {
    nav: { how: "कसे कार्य करते", features: "वैशिष्ट्ये", stories: "कथा", login: "लॉग इन", signup: "मोफत सुरू करा", dashboard: "डॅशबोर्ड" },
    badge: "AI-चालित · मोफत · भारतासाठी",
    heroLine1: "प्रत्येक मुलाला",
    heroLine2: "समजून घेतले पाहिजे।",
    heroSub: "LearnAble मजेदार खेळांद्वारे डिस्लेक्सिया, डिस्ग्राफिया आणि डिस्कॅल्क्युलियाची तपासणी करते — नंतर वैयक्तिक शिक्षण मार्ग तयार करते. मोफत. 15 मिनिटांत.",
    startBtn: "मोफत मूल्यांकन सुरू करा",
    howBtn: "हे कसे कार्य करते",
    statsItems: [
      { n: "3", label: "विकार तपासले" },
      { n: "10+", label: "शिक्षण खेळ" },
      { n: "3", label: "भाषा" },
      { n: "100%", label: "नेहमी मोफत" },
    ],
    disabilityTitle: "आम्ही काय तपासतो",
    disabilities: [
      { id: "dyslexia", color: "#7c3aed", bg: "#f5f3ff", icon: "📖", title: "डिस्लेक्सिया", tagline: "वाचन आणि शब्दलेखन", desc: "शब्द ओळखणे, शब्दलेखन आणि मजकूर समजण्यात अडचण. 10 पैकी 1 मुलाला प्रभावित करते.", signals: ["अक्षरे उलटवणे", "मंद वाचन", "फोनिक्स गोंधळ"], cta: "डिस्लेक्सिया चाचणी घ्या", href: "/assessment/dyslexia" },
      { id: "dysgraphia", color: "#0d9488", bg: "#f0fdfa", icon: "✍️", title: "डिस्ग्राफिया", tagline: "लेखन आणि मोटर कौशल्ये", desc: "हस्ताक्षर, अंतर आणि कागदावर विचार मांडण्यात अडचण.", signals: ["असंगत अक्षर आकार", "कमकुवत पेन्सिल पकड", "मंद लेखन"], cta: "डिस्ग्राफिया चाचणी घ्या", href: "/assessment/dysgraphia" },
      { id: "dyscalculia", color: "#ea580c", bg: "#fff7ed", icon: "🔢", title: "डिस्कॅल्क्युलिया", tagline: "संख्या आणि गणित", desc: "संख्या आणि गणिती संकल्पना समजण्यात अडचण — हे बुद्धिमत्तेबद्दल नाही.", signals: ["बोटांवर मोजणे", "वेळेशी संघर्ष", "संख्या उलटवणे"], cta: "डिस्कॅल्क्युलिया चाचणी घ्या", href: "/assessment/dyscalculia" },
    ],
    howTitle: "तीन टप्पे. पंधरा मिनिटे.",
    steps: [
      { n: "01", title: "खेळ खेळा", desc: "अनुकूली AI-चालित खेळ वाचन, लेखन आणि गणित कौशल्यांची चाचणी करतात.", icon: "🎮" },
      { n: "02", title: "तुमचा अहवाल मिळवा", desc: "जोखीम पातळी आणि विश्वास स्कोअरसह सविस्तर स्क्रीनिंग अहवाल मिळवा.", icon: "📊" },
      { n: "03", title: "शिकणे सुरू करा", desc: "वैयक्तिक गेम-आधारित शिक्षण मार्गांमध्ये प्रवेश करा. XP कमवा, स्ट्रीक राखा.", icon: "🚀" },
    ],
    featTitle: "वेगळ्या प्रकारे बनवले.",
    featSub: "कोणतीही साधारण क्विझ नाही. प्रत्येक वैशिष्ट्य शिकण्याच्या फरकांसह मुले कसे विचार करतात यावर आधारित डिझाइन केले आहे.",
    features: [
      { icon: "🧠", title: "पुरावा-आधारित इंजिन", desc: "प्रकाशित रूब्रिक्सवर आधारित स्क्रीनिंग — अंदाज नाही." },
      { icon: "🦉", title: "Owly AI शिक्षक", desc: "Groq-संचालित LLaMA 3.3 70B चॅटबॉट." },
      { icon: "📥", title: "हिंदी आणि मराठीत PDF अहवाल", desc: "इंग्रजी, हिंदी किंवा मराठीत व्यावसायिक अहवाल डाउनलोड करा." },
      { icon: "👨‍👩‍👧", title: "पालक डॅशबोर्ड", desc: "प्रगती चार्टसह PIN-संरक्षित दृश्य." },
      { icon: "🔊", title: "मजकूर-ते-भाषण", desc: "प्रत्येक प्रश्न मोठ्याने वाचता येतो." },
      { icon: "🔒", title: "100% खाजगी", desc: "सर्व डेटा तुमच्या ब्राउझरमध्ये राहतो. कोणताही सर्व्हर नाही." },
    ],
    testimonialsTitle: "कुटुंबे काय म्हणतात",
    testimonials: [
      { quote: "माझ्या मुलाला वर्षानुवर्षे वाचण्यात संघर्ष होता. मूल्यांकनानंतर, आम्हाला शेवटी त्याचे नाव मिळाले — आणि एक योजना.", name: "प्रिया शर्मा", role: "9 वर्षाच्या मुलाची आई, पुणे", seed: "priya" },
      { quote: "मराठीत डाउनलोड केलेला अहवाल आम्ही शेवटी आमच्या सासूबाईंसोबत शेअर करू शकलो.", name: "ऐश्वर्या कुलकर्णी", role: "पालक, नाशिक", seed: "aishwarya" },
      { quote: "एक विशेष शिक्षक म्हणून, मी LearnAble प्रत्येक शाळेला सुचवतो.", name: "श्री. रमेश पाटील", role: "विशेष शिक्षक, मुंबई", seed: "ramesh" },
    ],
    ctaTitle: "तुमच्या मुलाची क्षमता वाट पाहत आहे.",
    ctaSub: "मोफत स्क्रीनिंग. क्रेडिट कार्ड नाही. सुरू करण्यासाठी खाते आवश्यक नाही.",
    ctaBtn: "मोफत मूल्यांकन सुरू करा →",
    ctaBtnUser: "डॅशबोर्डवर जा →",
    footerNote: "वेगळ्या प्रकारे शिकणाऱ्या प्रत्येक मुलासाठी ❤️ ने बनवले.",
  },
};

// ─── Lang Switcher ────────────────────────────────────────────────────────────
function LangSwitcher({ lang, setLang }: { lang: Lang; setLang: (l: Lang) => void }) {
  return (
    <div className="flex items-center gap-1 p-1 rounded-full bg-gray-100/80 backdrop-blur-sm border border-gray-200/50 shadow-inner">
      {(["en", "hi", "mr"] as Lang[]).map((code) => (
        <button key={code} onClick={() => setLang(code)}
          className={`px-3 py-1.5 rounded-full text-xs font-bold transition-all duration-300 ${
            lang === code 
              ? "bg-white text-violet-700 shadow-sm ring-1 ring-black/5 scale-100" 
              : "text-gray-500 hover:text-gray-900 hover:bg-gray-200/50 scale-95"
          }`}>
          {code === "en" ? "EN" : code === "hi" ? "हि" : "म"}
        </button>
      ))}
    </div>
  );
}

// ─── Disability Illustration SVGs ───────────────────────────────────────────
function DyslexiaIllustration() {
  return (
    <svg viewBox="0 0 280 200" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-full h-full drop-shadow-xl">
      <rect x="20" y="30" width="240" height="140" rx="20" fill="url(#dyslexiaGradient)" />
      <rect x="40" y="55" width="120" height="12" rx="6" fill="white" opacity="0.6" />
      <rect x="40" y="75" width="160" height="12" rx="6" fill="white" opacity="0.8" />
      <rect x="40" y="95" width="90" height="12" rx="6" fill="white" opacity="0.6" />
      <rect x="40" y="115" width="140" height="12" rx="6" fill="white" opacity="0.7" />
      <rect x="40" y="135" width="100" height="12" rx="6" fill="white" opacity="0.4" />
      {/* Highlighted word */}
      <rect x="138" y="71" width="44" height="20" rx="8" fill="white" className="animate-pulse" />
      <text x="160" y="85" textAnchor="middle" fill="#7c3aed" fontSize="11" fontWeight="900">was</text>
      {/* Confusion arrow */}
      <text x="195" y="85" fill="white" fontSize="12" fontWeight="bold">→ saw?</text>
      
      {/* FIX: Moved backdropFilter into the style object */}
      <circle cx="210" cy="55" r="22" fill="rgba(255,255,255,0.2)" style={{ backdropFilter: "blur(8px)" }} stroke="white" strokeWidth="2" />
      <text x="210" y="61" textAnchor="middle" fontSize="18">🔍</text>
      <defs>
        <linearGradient id="dyslexiaGradient" x1="20" y1="30" x2="260" y2="170" gradientUnits="userSpaceOnUse">
          <stop stopColor="#a855f7" />
          <stop offset="1" stopColor="#7c3aed" />
        </linearGradient>
      </defs>
    </svg>
  );
}

function DysgraphiaIllustration() {
  return (
    <svg viewBox="0 0 280 200" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-full h-full drop-shadow-xl">
      <rect x="20" y="20" width="240" height="160" rx="20" fill="url(#dysgraphiaGradient)" />
      {[60, 80, 100, 120, 140, 160].map((y, i) => (
        <line key={i} x1="40" y1={y} x2="240" y2={y} stroke="white" strokeWidth="1.5" opacity="0.3" />
      ))}
      <path d="M 45 75 Q 55 65 65 75 Q 75 85 85 72 Q 95 60 105 74 Q 115 88 125 71 Q 135 55 145 73 Q 155 90 165 70 Q 175 52 185 72" stroke="white" strokeWidth="4" fill="none" strokeLinecap="round" opacity="0.9" />
      <path d="M 45 100 Q 60 90 75 102 Q 90 114 105 98 Q 120 82 135 100 Q 150 118 165 99" stroke="white" strokeWidth="4" fill="none" strokeLinecap="round" opacity="0.6" />
      <g transform="translate(190, 40) rotate(35)">
        <rect x="-6" y="-30" width="12" height="50" rx="3" fill="#fbbf24" />
        <polygon points="-6,20 6,20 0,34" fill="#fcd34d" />
        <rect x="-6" y="-30" width="12" height="10" rx="3" fill="#f3f4f6" />
      </g>
      <defs>
        <linearGradient id="dysgraphiaGradient" x1="20" y1="20" x2="260" y2="180" gradientUnits="userSpaceOnUse">
          <stop stopColor="#14b8a6" />
          <stop offset="1" stopColor="#0d9488" />
        </linearGradient>
      </defs>
    </svg>
  );
}

function DyscalculiaIllustration() {
  return (
    <svg viewBox="0 0 280 200" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-full h-full drop-shadow-xl">
      <rect x="20" y="20" width="240" height="160" rx="20" fill="url(#dyscalculiaGradient)" />
      <text x="140" y="90" textAnchor="middle" fill="white" fontSize="34" fontWeight="900" opacity="0.3">7 + 8 = ?</text>
      <text x="100" y="130" textAnchor="middle" fill="white" fontSize="24" fontWeight="bold" opacity="0.8">13</text>
      <line x1="72" y1="118" x2="128" y2="138" stroke="#ef4444" strokeWidth="4" strokeLinecap="round" />
      {[0,1,2,3,4].map((i) => (
        <g key={i} transform={`translate(${155 + i * 14}, 110)`}>
          <rect x="-4" y="-20" width="8" height="26" rx="4" fill="#fed7aa" />
          <ellipse cx="0" cy="-20" rx="4" ry="4" fill="#ffedd5" />
        </g>
      ))}
      <text x="168" y="148" textAnchor="middle" fill="white" fontSize="10" fontWeight="bold">counting on fingers</text>
      
      {/* FIX: Moved backdropFilter into the style object */}
      <circle cx="68" cy="90" r="28" fill="rgba(255,255,255,0.2)" style={{ backdropFilter: "blur(4px)" }} stroke="white" strokeWidth="3" />
      <line x1="68" y1="90" x2="68" y2="68" stroke="white" strokeWidth="3" strokeLinecap="round" />
      <line x1="68" y1="90" x2="84" y2="96" stroke="white" strokeWidth="2.5" strokeLinecap="round" />
      <text x="68" y="133" textAnchor="middle" fill="white" fontSize="10" fontWeight="bold">what time is it?</text>
      <defs>
        <linearGradient id="dyscalculiaGradient" x1="20" y1="20" x2="260" y2="180" gradientUnits="userSpaceOnUse">
          <stop stopColor="#f97316" />
          <stop offset="1" stopColor="#ea580c" />
        </linearGradient>
      </defs>
    </svg>
  );
}

const illustrations = [DyslexiaIllustration, DysgraphiaIllustration, DyscalculiaIllustration];

// ─── Hero Mockup ──────────────────────────────────────────────────────────────
function HeroMockup() {
  return (
    <div className="relative w-full max-w-md mx-auto group">
      {/* Dynamic Animated Glow */}
      <div className="absolute -inset-1 blur-3xl opacity-50 bg-gradient-to-r from-violet-600 via-teal-500 to-orange-500 rounded-[40px] animate-blob group-hover:opacity-75 transition duration-500" />

      {/* Glass Phone frame */}
      <div className="relative rounded-[40px] overflow-hidden shadow-2xl bg-gray-900/90 backdrop-blur-xl border border-white/10 ring-1 ring-white/20">
        {/* Status bar */}
        <div className="flex justify-between items-center px-6 pt-5 pb-2">
          <span className="text-white/60 text-xs font-bold">9:41</span>
          <div className="w-28 h-6 rounded-full bg-black shrink-0" />
          <div className="flex gap-1.5">
            {[...Array(3)].map((_, i) => <div key={i} className="w-1.5 h-1.5 rounded-full bg-white/60" />)}
          </div>
        </div>

        {/* App header */}
        <div className="px-6 py-4 flex items-center justify-between border-b border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl flex items-center justify-center text-xs font-black text-white bg-gradient-to-br from-violet-500 to-fuchsia-600 shadow-lg shadow-violet-500/30">
              L
            </div>
            <span className="text-white font-black text-sm tracking-wide">LearnAble</span>
          </div>
          <div className="flex items-center gap-3 bg-white/5 px-3 py-1.5 rounded-full">
            <span className="text-yellow-400 text-xs font-black flex items-center gap-1">🔥 7</span>
            <div className="w-px h-3 bg-white/20" />
            <span className="text-rose-400 text-xs font-black flex items-center gap-1">❤️ 5</span>
          </div>
        </div>

        {/* Dashboard content */}
        <div className="p-6 space-y-4">
          <p className="text-white/40 text-[10px] font-bold uppercase tracking-widest">Today's Focus</p>

          {/* Assessment cards */}
          {[
            { label: "Dyslexia", color: "#8b5cf6", bg: "bg-violet-500/10", border: "border-violet-500/20", pct: 72, risk: "Moderate", icon: "📖" },
            { label: "Dysgraphia", color: "#14b8a6", bg: "bg-teal-500/10", border: "border-teal-500/20", pct: 88, risk: "Low", icon: "✍️" },
            { label: "Dyscalculia", color: "#f97316", bg: "bg-orange-500/10", border: "border-orange-500/20", pct: 45, risk: "High", icon: "🔢" },
          ].map((item) => (
            <div key={item.label} className={`rounded-2xl p-4 flex items-center gap-4 border ${item.bg} ${item.border} hover:scale-[1.02] transition-transform cursor-pointer`}>
              <div className="w-10 h-10 rounded-full flex items-center justify-center bg-white/5 text-xl shrink-0">
                {item.icon}
              </div>
              <div className="flex-1">
                <div className="flex justify-between mb-2">
                  <span className="text-white/90 text-sm font-bold">{item.label}</span>
                  <span className="text-xs font-black" style={{ color: item.risk === "High" ? "#f87171" : item.risk === "Moderate" ? "#fbbf24" : "#34d399" }}>
                    {item.risk}
                  </span>
                </div>
                <div className="h-2 rounded-full bg-black/40 overflow-hidden">
                  <div className="h-full rounded-full transition-all duration-1000 ease-out relative" style={{ width: `${item.pct}%`, background: item.color }}>
                    <div className="absolute inset-0 bg-white/20 w-full animate-shimmer" style={{ transform: "skewX(-20deg)" }} />
                  </div>
                </div>
              </div>
            </div>
          ))}

          {/* XP bar */}
          <div className="rounded-2xl p-4 mt-6 bg-gradient-to-br from-violet-600/20 to-fuchsia-600/20 border border-violet-500/30 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-violet-500/20 blur-3xl rounded-full" />
            <div className="flex justify-between mb-3 relative z-10">
              <span className="text-violet-200 text-xs font-bold flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-violet-400 animate-pulse" /> Level 4
              </span>
              <span className="text-violet-300 text-xs font-medium">340 / 400 XP</span>
            </div>
            <div className="h-2.5 rounded-full bg-black/40 relative z-10 overflow-hidden">
              <div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-fuchsia-500 w-[85%]" />
            </div>
          </div>
        </div>

        {/* Bottom nav */}
        <div className="flex justify-around px-6 py-5 bg-gray-900/50 backdrop-blur-md border-t border-white/5">
          {["🏠", "🎮", "📊", "👤"].map((icon, i) => (
            <button key={i} className={`text-xl transition-all duration-300 ${i===0 ? "opacity-100 scale-110 drop-shadow-md" : "opacity-40 hover:opacity-100 hover:-translate-y-1"}`}>
              {icon}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── Animated Counter ─────────────────────────────────────────────────────────
function Counter({ target, suffix = "" }: { target: number; suffix?: string }) {
  const [val, setVal] = useState(0);
  useEffect(() => {
    let s = 0;
    const step = Math.ceil(target / 40);
    const t = setInterval(() => {
      s += step;
      if (s >= target) { setVal(target); clearInterval(t); }
      else setVal(s);
    }, 30);
    return () => clearInterval(t);
  }, [target]);
  return <>{val}{suffix}</>;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
export default function Home() {
  const { user } = useAuth();
  const [lang, setLang] = useState<Lang>("en");
  const [activeDisability, setActiveDisability] = useState(0);
  const t = T[lang];

  useEffect(() => {
    const id = setInterval(() => setActiveDisability(p => (p + 1) % 3), 5000);
    return () => clearInterval(id);
  }, []);

  const Illustration = illustrations[activeDisability];
  const activeDis = t.disabilities[activeDisability];

  return (
    <div className="min-h-screen bg-[#fafcff] text-slate-900 selection:bg-violet-200 selection:text-violet-900 overflow-x-hidden">

      {/* ── Styles & Animations ── */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Inter:wght@400;500;600&display=swap');
        * { font-family: 'Inter', sans-serif; }
        h1,h2,h3,.font-display { font-family: 'Nunito', sans-serif; }
        
        @keyframes float { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-15px)} }
        @keyframes float-delayed { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-10px)} }
        @keyframes fadeUp { from{opacity:0;transform:translateY(30px)} to{opacity:1;transform:translateY(0)} }
        @keyframes blob { 0%,100%{transform:scale(1)} 50%{transform:scale(1.05)} }
        @keyframes shimmer { 0%{transform:translateX(-150%) skewX(-20deg)} 100%{transform:translateX(200%) skewX(-20deg)} }
        
        .fade-up { animation: fadeUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) both; }
        .delay-100 { animation-delay: 100ms; }
        .delay-200 { animation-delay: 200ms; }
        .float { animation: float 6s ease-in-out infinite; }
        .float-delayed { animation: float-delayed 7s ease-in-out infinite 2s; }
        
        .glass-card {
          background: rgba(255, 255, 255, 0.7);
          backdrop-filter: blur(16px);
          border: 1px solid rgba(255, 255, 255, 0.8);
          box-shadow: 0 4px 30px rgba(0, 0, 0, 0.03);
        }
      `}</style>

      {/* ══ NAV ══ */}
      <nav className="fixed w-full top-0 z-50 bg-white/70 backdrop-blur-xl border-b border-gray-200/50 transition-all duration-300">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex items-center gap-2.5 group">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center text-white text-base font-black bg-gradient-to-br from-violet-600 to-fuchsia-500 shadow-md shadow-violet-500/20 group-hover:shadow-violet-500/40 transition-shadow">
              L
            </div>
            <span className="font-black text-xl tracking-tight text-slate-900 group-hover:text-violet-600 transition-colors" style={{ fontFamily: "Nunito,sans-serif" }}>
              LearnAble
            </span>
          </Link>

          {/* Nav links */}
          <div className="hidden md:flex items-center gap-10">
            {[["/how-it-works", t.nav.how], ["/disabilities", t.nav.features], ["/#testimonials", t.nav.stories]].map(([href, label]) => (
              <Link key={href} href={href} className="text-sm font-semibold text-slate-500 hover:text-slate-900 transition-colors">
                {label}
              </Link>
            ))}
          </div>

          {/* Right */}
          <div className="flex items-center gap-4">
            <LangSwitcher lang={lang} setLang={setLang} />
            {user ? (
              <div className="flex items-center gap-3 pl-2 border-l border-gray-200">
                <Link href="/dashboard" className="px-5 py-2 rounded-full text-sm font-bold text-white bg-slate-900 hover:bg-slate-800 transition-colors shadow-lg shadow-slate-900/20">
                  {t.nav.dashboard}
                </Link>
                <Link href="/profile" className="ring-2 ring-white rounded-full shadow-sm hover:scale-105 transition-transform">
                  <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${user.name}`} className="w-9 h-9 rounded-full bg-violet-100" alt="Profile" />
                </Link>
              </div>
            ) : (
              <div className="flex items-center gap-3 pl-2 border-l border-gray-200">
                <Link href="/login" className="text-sm font-semibold text-slate-600 hover:text-slate-900 transition-colors hidden sm:block">
                  {t.nav.login}
                </Link>
                <Link href="/signup" className="relative group px-5 py-2.5 rounded-full text-sm font-bold text-white overflow-hidden shadow-lg shadow-violet-500/25 hover:shadow-violet-500/40 transition-all hover:-translate-y-0.5">
                  <span className="absolute inset-0 w-full h-full bg-gradient-to-r from-violet-600 to-fuchsia-500" />
                  <span className="absolute inset-0 w-full h-full opacity-0 group-hover:opacity-100 bg-gradient-to-r from-fuchsia-500 to-violet-600 transition-opacity duration-500" />
                  <span className="relative z-10">{t.nav.signup}</span>
                </Link>
              </div>
            )}
          </div>
        </div>
      </nav>

      {/* ══ HERO ══ */}
      <section className="relative pt-32 pb-40 px-6 lg:min-h-screen flex items-center">
        {/* Animated Mesh Gradients */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
          <div className="absolute top-[-10%] left-[-10%] w-[50vw] h-[50vw] rounded-full bg-violet-400/20 mix-blend-multiply filter blur-[100px] animate-blob" />
          <div className="absolute top-[20%] right-[-10%] w-[40vw] h-[40vw] rounded-full bg-teal-300/20 mix-blend-multiply filter blur-[100px] animate-blob" style={{ animationDelay: "2s" }} />
          <div className="absolute bottom-[-20%] left-[20%] w-[40vw] h-[40vw] rounded-full bg-orange-200/20 mix-blend-multiply filter blur-[100px] animate-blob" style={{ animationDelay: "4s" }} />
        </div>

        <div className="max-w-7xl mx-auto relative z-10 w-full">
          <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center">
            
            {/* Left Copy */}
            <div className="fade-up pt-10">
              <div className="inline-flex items-center gap-2.5 px-4 py-2 rounded-full text-xs font-bold mb-8 bg-white/60 backdrop-blur-md border border-violet-100 shadow-sm text-violet-700">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-violet-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-violet-500"></span>
                </span>
                {t.badge}
              </div>

              <h1 className="font-display text-5xl md:text-6xl lg:text-[72px] font-black leading-[1.05] mb-6 tracking-tight text-slate-900">
                {t.heroLine1}<br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-600 via-fuchsia-500 to-orange-500 relative">
                  {t.heroLine2}
                  {/* Subtle underline SVG */}
                  <svg className="absolute w-full h-3 -bottom-1 left-0 text-fuchsia-500/30" viewBox="0 0 100 10" preserveAspectRatio="none">
                    <path d="M0 5 Q 50 10 100 5" stroke="currentColor" strokeWidth="4" fill="transparent" strokeLinecap="round" />
                  </svg>
                </span>
              </h1>

              <p className="text-lg md:text-xl leading-relaxed mb-10 max-w-lg text-slate-600 font-medium">
                {t.heroSub}
              </p>

              {/* CTAs */}
              <div className="flex flex-col sm:flex-row gap-4 mb-12">
                <Link href="/assessment/dyslexia" className="group relative inline-flex items-center justify-center gap-2 px-8 py-4 rounded-2xl text-base font-bold text-white overflow-hidden shadow-xl shadow-violet-500/25 hover:shadow-violet-500/40 hover:-translate-y-1 transition-all duration-300">
                  <div className="absolute inset-0 bg-gradient-to-r from-violet-600 to-fuchsia-600" />
                  <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300 ease-out" />
                  <span className="relative flex items-center gap-2">🚀 {t.startBtn}</span>
                </Link>
                <Link href="/how-it-works" className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-2xl text-base font-bold text-slate-700 bg-white border border-slate-200 shadow-sm hover:shadow-md hover:-translate-y-1 hover:border-slate-300 transition-all duration-300">
                    {t.howBtn} <span className="text-slate-400 group-hover:translate-x-1 transition-transform">→</span>
                </Link>
                <Link href="/disabilities" className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-2xl text-base font-bold text-slate-700 bg-white border border-slate-200 shadow-sm hover:shadow-md hover:-translate-y-1 hover:border-slate-300 transition-all duration-300">
                    {t.howBtn} <span className="text-slate-400 group-hover:translate-x-1 transition-transform">→</span>
                </Link>
              </div>
              
              {/* Trust Indicators */}
              <div className="flex items-center gap-4 text-sm font-semibold text-slate-500">
                <div className="flex -space-x-2">
                  {['ramesh', 'priya', 'aishwarya'].map(seed => (
                    <img key={seed} src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`} className="w-8 h-8 rounded-full border-2 border-[#fafcff] bg-gray-100" alt="User" />
                  ))}
                </div>
                <p>Trusted by <span className="text-slate-900">10,000+</span> parents & educators</p>
              </div>
            </div>

            {/* Right Mockup */}
            <div className="hidden lg:block relative z-10 fade-up delay-200">
              {/* Decorative floating elements */}
              <div className="absolute top-10 -left-10 w-24 h-24 bg-white rounded-2xl shadow-xl border border-white/50 glass-card float flex flex-col items-center justify-center p-3 z-20">
                 <span className="text-3xl mb-1">🧠</span>
                 <span className="text-[10px] font-bold text-slate-500 text-center uppercase tracking-wider">AI Powered</span>
              </div>
              <div className="absolute bottom-20 -right-8 w-28 h-24 bg-white rounded-2xl shadow-xl border border-white/50 glass-card float-delayed flex flex-col items-center justify-center p-3 z-20">
                 <span className="text-xl font-black text-emerald-500 mb-1">+450 XP</span>
                 <span className="text-[10px] font-bold text-slate-500 text-center uppercase tracking-wider">Streak Kept!</span>
              </div>
              
              <div className="float">
                <HeroMockup />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ══ STATS STRIP (Overlapping) ══ */}
      <div className="relative z-20 max-w-6xl mx-auto px-6 -mt-20 fade-up delay-200">
        <div className="glass-card rounded-[32px] p-8 md:p-12 grid grid-cols-2 md:grid-cols-4 gap-8 text-center divide-x divide-gray-200/50">
          {[
            { target: 3, suffix: "", label: t.statsItems[0].label, from: "from-violet-600", to: "to-fuchsia-500" },
            { target: 10, suffix: "+", label: t.statsItems[1].label, from: "from-teal-500", to: "to-emerald-500" },
            { target: 3, suffix: "", label: t.statsItems[2].label, from: "from-orange-500", to: "to-amber-500" },
            { target: 100, suffix: "%", label: t.statsItems[3].label, from: "from-blue-500", to: "to-indigo-500" },
          ].map(({ target, suffix, label, from, to }, idx) => (
            <div key={label} className={`flex flex-col items-center justify-center ${idx % 2 === 0 ? 'border-none md:border-solid' : 'border-none'}`}>
              <p className={`text-4xl md:text-5xl font-black mb-2 bg-gradient-to-br ${from} ${to} text-transparent bg-clip-text`} style={{ fontFamily: "Nunito,sans-serif" }}>
                <Counter target={target} suffix={suffix} />
              </p>
              <p className="text-sm font-semibold text-slate-500">{label}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ══ WHAT WE SCREEN ══ */}
      <section id="disabilities" className="py-32 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16 fade-up">
            <h2 className="text-4xl md:text-5xl font-black mb-4 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>{t.disabilityTitle}</h2>
            <p className="text-lg text-slate-500">Select a tab to explore each learning difference</p>
          </div>

          {/* Tab selector */}
          <div className="flex justify-center gap-3 mb-12 flex-wrap">
            {t.disabilities.map((d, i) => (
              <button key={d.id} onClick={() => setActiveDisability(i)}
                className={`flex items-center gap-2.5 px-6 py-3.5 rounded-full text-sm font-bold transition-all duration-300 ${
                  activeDisability === i 
                    ? "text-white shadow-xl scale-105" 
                    : "bg-white text-slate-600 hover:bg-slate-50 border border-slate-200 hover:scale-105 hover:shadow-md"
                }`}
                style={{ background: activeDisability === i ? d.color : "", boxShadow: activeDisability === i ? `0 10px 25px -5px ${d.color}66` : "" }}>
                <span className="text-lg">{d.icon}</span> {d.title}
              </button>
            ))}
          </div>

          {/* Active panel - Glass morphic layout */}
          <div className="relative rounded-[40px] p-1 overflow-hidden transition-all duration-700 ease-in-out" style={{ background: `linear-gradient(135deg, ${activeDis.color}15, ${activeDis.color}05)` }}>
            <div className="absolute inset-0 bg-white/40 backdrop-blur-xl" />
            <div className="relative grid md:grid-cols-2 gap-10 items-center bg-white/80 rounded-[36px] p-8 md:p-14 border border-white shadow-sm">
              
              {/* Info */}
              <div className="order-2 md:order-1">
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-black mb-6 border" style={{ background: `${activeDis.color}10`, color: activeDis.color, borderColor: `${activeDis.color}20` }}>
                  {activeDis.icon} {activeDis.tagline}
                </div>
                <h3 className="text-4xl font-black mb-5 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>
                  {activeDis.title}
                </h3>
                <p className="text-lg leading-relaxed mb-8 text-slate-600 font-medium">{activeDis.desc}</p>

                {/* Signals */}
                <div className="space-y-3 mb-10 bg-slate-50 p-6 rounded-3xl border border-slate-100">
                  <p className="text-xs font-black uppercase tracking-widest text-slate-400 mb-4">Common Signs</p>
                  {activeDis.signals.map((s) => (
                    <div key={s} className="flex items-center gap-3">
                      <div className="w-6 h-6 rounded-full flex items-center justify-center text-white text-xs shrink-0 shadow-sm" style={{ background: activeDis.color }}>✓</div>
                      <span className="text-sm font-bold text-slate-700">{s}</span>
                    </div>
                  ))}
                </div>

                <Link href={activeDis.href} className="group inline-flex items-center gap-3 px-8 py-4 rounded-2xl text-sm font-bold text-white transition-all hover:-translate-y-1" style={{ background: activeDis.color, boxShadow: `0 10px 25px -5px ${activeDis.color}66` }}>
                  {activeDis.cta} <span className="group-hover:translate-x-1 transition-transform">→</span>
                </Link>
              </div>

              {/* Illustration */}
              <div className="order-1 md:order-2 h-64 md:h-80 relative flex items-center justify-center">
                <div className="absolute inset-0 bg-gradient-to-br from-white/50 to-transparent rounded-[32px] blur-xl" />
                <div className="relative w-full h-full transform hover:scale-105 transition-transform duration-500">
                  <Illustration />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ══ HOW IT WORKS (Modern Steps) ══ */}
      <section id="how" className="py-24 px-6 bg-white relative">
        <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-gray-200 to-transparent" />
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-20 fade-up">
            <h2 className="text-4xl md:text-5xl font-black mb-4 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>{t.howTitle}</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8 relative">
            {/* Connector line for desktop */}
            <div className="hidden md:block absolute top-12 left-[15%] right-[15%] h-0.5 bg-gradient-to-r from-violet-200 via-teal-200 to-orange-200 z-0" />

            {t.steps.map((step, i) => (
              <div key={i} className="relative z-10 flex flex-col items-center text-center group fade-up" style={{ animationDelay: `${i * 150}ms` }}>
                <div className="w-24 h-24 rounded-[32px] flex items-center justify-center text-4xl mb-8 bg-white shadow-[0_8px_30px_rgb(0,0,0,0.06)] border border-gray-100 group-hover:-translate-y-2 transition-transform duration-300 rotate-3 group-hover:rotate-0">
                  {step.icon}
                </div>
                <div className="inline-flex items-center justify-center px-3 py-1 rounded-full bg-slate-100 text-slate-500 text-xs font-black tracking-widest mb-4">
                  STEP {step.n}
                </div>
                <h3 className="text-2xl font-black mb-3 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>{step.title}</h3>
                <p className="text-base text-slate-500 leading-relaxed max-w-xs">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ FEATURES (Bento Grid) ══ */}
      <section id="features" className="py-32 px-6 relative bg-slate-50">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16 fade-up">
            <h2 className="text-4xl md:text-5xl font-black mb-5 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>{t.featTitle}</h2>
            <p className="max-w-2xl mx-auto text-lg text-slate-500 font-medium">{t.featSub}</p>
          </div>

          <div className="grid md:grid-cols-3 md:grid-rows-2 gap-6 fade-up delay-100">
            {/* Big Feature 1 */}
            <div className="md:col-span-2 bg-white rounded-[32px] p-8 md:p-10 border border-slate-200 shadow-sm hover:shadow-xl transition-shadow relative overflow-hidden group">
              <div className="absolute right-0 bottom-0 w-64 h-64 bg-violet-100 rounded-full blur-3xl -mr-20 -mb-20 transition-transform group-hover:scale-110" />
              <div className="relative z-10">
                <span className="text-5xl block mb-6">{t.features[0].icon}</span>
                <h3 className="text-2xl font-black mb-3 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>{t.features[0].title}</h3>
                <p className="text-slate-500 text-lg leading-relaxed max-w-md">{t.features[0].desc}</p>
              </div>
            </div>

            {/* Feature 2 */}
            <div className="bg-gradient-to-br from-slate-800 to-slate-900 text-white rounded-[32px] p-8 border border-slate-700 shadow-xl relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-32 h-32 bg-teal-500/20 rounded-full blur-2xl transition-transform group-hover:scale-150" />
              <div className="relative z-10">
                <span className="text-5xl block mb-6">{t.features[1].icon}</span>
                <h3 className="text-xl font-black mb-3 text-white" style={{ fontFamily: "Nunito,sans-serif" }}>{t.features[1].title}</h3>
                <p className="text-slate-300 leading-relaxed">{t.features[1].desc}</p>
              </div>
            </div>

            {/* Feature 3, 4, 5 */}
            {t.features.slice(2, 5).map((f, i) => (
              <div key={i} className="bg-white rounded-[32px] p-8 border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                <span className="text-4xl block mb-5 bg-slate-50 w-16 h-16 rounded-2xl flex items-center justify-center border border-slate-100">{f.icon}</span>
                <h3 className="text-lg font-black mb-2 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>{f.title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ TESTIMONIALS ══ */}
      <section id="testimonials" className="py-32 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16 fade-up">
            <h2 className="text-4xl md:text-5xl font-black mb-4 text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>{t.testimonialsTitle}</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {t.testimonials.map((item, i) => (
              <div key={i} className="bg-white rounded-[32px] p-8 md:p-10 flex flex-col justify-between border border-slate-200 shadow-sm hover:shadow-2xl hover:shadow-violet-500/10 transition-shadow duration-500 fade-up" style={{ animationDelay: `${i * 150}ms` }}>
                <div className="mb-8 relative">
                  <span className="text-6xl text-violet-200 absolute -top-4 -left-2 font-serif opacity-50">"</span>
                  <p className="text-base font-medium leading-relaxed text-slate-600 relative z-10 italic pt-4">
                    {item.quote}
                  </p>
                </div>
                <div className="flex items-center gap-4 pt-6 border-t border-slate-100">
                  <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${item.seed}`} alt={item.name} className="w-12 h-12 rounded-full bg-violet-50 ring-2 ring-white shadow-sm" />
                  <div>
                    <p className="font-bold text-slate-900 text-sm">{item.name}</p>
                    <p className="text-xs font-semibold text-slate-400 mt-0.5">{item.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ CTA (Immersive) ══ */}
      <section className="py-24 px-6 mb-10">
        <div className="max-w-5xl mx-auto rounded-[40px] p-12 md:p-20 text-center relative overflow-hidden shadow-2xl bg-slate-900">
          {/* Deep space blobs */}
          <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
            <div className="absolute -top-40 -left-40 w-96 h-96 rounded-full bg-violet-600/40 blur-[80px]" />
            <div className="absolute -bottom-40 -right-40 w-96 h-96 rounded-full bg-teal-500/30 blur-[80px]" />
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-full bg-[url('https://www.transparenttextures.com/patterns/stardust.png')] opacity-20" />
          </div>

          <div className="relative z-10 fade-up">
            <h2 className="text-4xl md:text-6xl font-black text-white mb-6 tracking-tight" style={{ fontFamily: "Nunito,sans-serif" }}>
              {t.ctaTitle}
            </h2>
            <p className="text-lg md:text-xl font-medium mb-12 text-slate-300 max-w-2xl mx-auto">
              {t.ctaSub}
            </p>
            <Link href={user ? "/dashboard" : "/signup"} className="group relative inline-flex items-center justify-center px-10 py-5 rounded-full text-lg font-black text-white overflow-hidden shadow-2xl hover:scale-105 transition-transform duration-300">
              <span className="absolute inset-0 bg-gradient-to-r from-violet-500 via-fuchsia-500 to-orange-500 group-hover:bg-[length:200%_auto] animate-[shimmer_3s_linear_infinite]" />
              <span className="relative flex items-center gap-2">
                {user ? t.ctaBtnUser : t.ctaBtn} 
              </span>
            </Link>
          </div>
        </div>
      </section>

      {/* ══ FOOTER ══ */}
      <footer className="px-6 py-16 bg-white border-t border-slate-200">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center gap-8 mb-12">
            <div className="flex items-center gap-2.5">
              <div className="w-10 h-10 rounded-xl flex items-center justify-center text-white text-base font-black bg-gradient-to-br from-violet-600 to-fuchsia-500 shadow-md">
                L
              </div>
              <span className="font-black text-2xl text-slate-900" style={{ fontFamily: "Nunito,sans-serif" }}>LearnAble</span>
            </div>
            
            <div className="flex flex-wrap justify-center gap-8 text-sm font-semibold text-slate-500">
              {[
                ["/assessment/dyslexia", "Assessment"],
                ["/dashboard", "Dashboard"],
                ["/report", "Report"],
                ["/specialists", "Specialists"],
                ["/parent", "For Parents"],
              ].map(([href, label]) => (
                <Link key={href} href={href} className="hover:text-violet-600 transition-colors">{label}</Link>
              ))}
            </div>
            
            <LangSwitcher lang={lang} setLang={setLang} />
          </div>
          
          <div className="pt-8 flex flex-col items-center justify-center border-t border-slate-100 text-sm font-medium text-slate-400">
            <p>© {new Date().getFullYear()} LearnAble. {t.footerNote}</p>
          </div>
        </div>
      </footer>
    </div>
  );
}